### ISSUE TITLE
Missing package: mxnet

### ISSUE THREAD

**Issue by muddyknee** [piwheels/packages#103]
Package name: mxnet
Issue type: not latest version and the version it does install is 64bit not 32 bit.
Link to PyPI page: https://pypi.org/project/mxnet
Link to piwheels page: https://www.piwheels.org/project/mxnet
Version: mxnet-1.6.0 
Python version:  3.7 
I am the maintainer:/No
More information:

```
$ sudo pip3 install mxnet
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting mxnet
  Using cached https://files.pythonhosted.org/packages/81/f5/d79b5b40735086ff1100c680703e0f3efc830fa455e268e9e96f3c857e93/mxnet-1.6.0-py2.py3-none-any.whl
Requirement already satisfied: numpy<2.0.0,>1.16.0 in /usr/lib/python3/dist-packages (from mxnet) (1.16.2)
Requirement already satisfied: graphviz<0.9.0,>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from mxnet) (0.8.4)
Requirement already satisfied: requests<3,>=2.20.0 in /usr/lib/python3/dist-packages (from mxnet) (2.21.0)
Installing collected packages: mxnet
Successfully installed mxnet-1.6.0 $ date
Sun 05 Apr 2020 02:43:23 PM BST

Python 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/mxnet/__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "/usr/local/lib/python3.7/dist-packages/mxnet/context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "/usr/local/lib/python3.7/dist-packages/mxnet/base.py", line 214, in <module>
    _LIB = _load_lib()
  File "/usr/local/lib/python3.7/dist-packages/mxnet/base.py", line 205, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.7/dist-packages/mxnet/libmxnet.so: wrong ELF class: ELFCLASS64
>>> 
```

**Comment by bennuttall** [comment]
This package has no source distribution - there's nothing to build from. They only provide wheels on PyPI - although they provide a pure Python wheel (that should work on any architecture) - it's presumably missing some functionality otherwise I don't know why the other platform wheels would be available.

There's nothing piwheels can do to build this package. The version you downloaded didn't come from piwheels, it came from PyPI. You'll have to take this up with the upstream project maintainers.
