### ISSUE TITLE
Missing package: pyscf

### ISSUE THREAD

**Issue by mucheinz** [piwheels/packages#134]
Package name: pyscf

Issue type: Missing package
Link to PyPI page: https://pypi.org/project/pyscf
Link to piwheels page: https://www.piwheels.org/project/pyscf/
Version: 1.7.3 (1.4.6 and higher)
Python version: all
I am the maintainer: No
More information:

Please use code blocks where appropriate:

```bash
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pyscf
  Downloading https://files.pythonhosted.org/packages/83/81/d7468533be1cf92ebc8fd04f47ef75ccecbcfeec3cdd064a71a5d657c84b/pyscf-1.7.3.tar.gz (23.3MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kyywsy79/pyscf/setup.py", line 245, in <module>
        raise RuntimeError
    RuntimeError
    ****************************************************************
    *** WARNING: BLAS library not found.
    * You can include the BLAS library in the global environment LDFLAGS, eg
    *   export LDFLAGS='-L/path/to/blas/lib -lblas'
    * or specify the BLAS library path in  PYSCF_INC_DIR
    *   export PYSCF_INC_DIR=/path/to/blas/lib:/path/to/other/lib
    ****************************************************************

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-                                                                                                                                  $
```

This can be overcome by issuing  
```
sudo apt-get install libopenblas-dev
```
next error then is:

```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pyscf
  Using cached https://files.pythonhosted.org/packages/83/81/d7468533be1cf92ebc8fd04f47ef75ccecbcfeec3cdd064a71a5d657c84b/pyscf-1.7.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-n22q10cu/pyscf/setup.py", line 354, in <module>
        raise RuntimeError
    RuntimeError
    ****************************************************************
    *** WARNING: libcint library not found.
    * You can download libcint library from http://github.com/sunqm/libcint
    * May need to set PYSCF_INC_DIR if libcint library was not installed in the
    * system standard install path (/usr, /usr/local, etc). Eg
    *   export PYSCF_INC_DIR=/path/to/libcint:/path/to/other/lib
    ****************************************************************
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-n22q10cu/pyscf/
```

**Comment by bennuttall** [comment]
We don't generally install third party libraries on the builders, so unless it's available as a Debian package we're unlikely to include it.

**Comment by sunqm** [comment]
When building pyscf pypi wheels, it needs first to build libxc and libcint. These libraries are then copied to pyscf build directories. Last is setup.py. Hope it helps.

Is it enough for raspberry Pi if a arm64 wheel is provided?

**Comment by bennuttall** [comment]
Only for users of the aarch64 image (beta), which is rare. Most use the armv7 OS.

Are there Debian packages which we can install to fix this build?

**Comment by MichaIng** [comment]
Builds here currently fail since piwheels builders are not allowed to Git clone via HTTPS, which is what this build attempts:
```
2025-10-23T06:10:48,612   [  2%] Performing download step (git clone) for 'libcint'
2025-10-23T06:10:48,645   Cloning into 'libcint'...
2025-10-23T06:10:48,689   fatal: transport 'https' not allowed
2025-10-23T06:10:48,707   Cloning into 'libcint'...
2025-10-23T06:10:48,744   fatal: transport 'https' not allowed
2025-10-23T06:10:48,761   Cloning into 'libcint'...
2025-10-23T06:10:48,799   fatal: transport 'https' not allowed
2025-10-23T06:10:48,814   Had to git clone more than once: 3 times.
2025-10-23T06:10:48,815   CMake Error at /tmp/pip-wheel-unj2usv3/pyscf_097a9ad98c7943b2bad17f6006b676fb/build/temp.linux-armv7l/deps/tmp/libcint-gitclone.cmake:50 (message):
2025-10-23T06:10:48,816     Failed to clone repository: 'https://github.com/sunqm/libcint.git'
```

**Comment by bennuttall** [comment]
Yeah this is an upstream issue. The maintainers shouldn't be relying on github for a build.

**Comment by MichaIng** [comment]
Agreed, proper solution should be to add libcint sources as submodule to the repo and to the sdist that way. It grows that sdist, but for users, without the extra Git clone, overall traffic and processing is smaller.
