### ISSUE TITLE
Missing package: bchess

### ISSUE THREAD

**Issue by magv** [piwheels/packages#219]
Package name: bchess
Link to PyPI page: https://pypi.org/project/bchess
Link to piwheels page: https://www.piwheels.org/project/bchess
Version: all
Python version: all
I am the maintainer: Yes
More information:

Hi, all. On the piwheels project page all builds for bchess are listed as failing; on the other hand I can `pip3 install --user bchess` without any problems on RPi 4 (Raspbian GNU/Linux 10) with Python 3.7 and PIP 21.1.1 (it does take a while, which is why it would be great if piwheels had a prebuilt version). Is it possible to check the build logs and figure out why is it failing?

I actually suspect one possible reason: bchess is using `pyproject.toml` which is only supported in PIP >=20.1; maybe you are using an old version on your build machines? Other than this, I'm not sure what the problem might be.

**Comment by bennuttall** [comment]
Here's the output from the latest version on cp37m:

```
2021-07-03T08:07:52,974   The Meson build system
2021-07-03T08:07:52,974   Version: 0.58.1
2021-07-03T08:07:52,974   Source dir: /tmp/pip-wheel-oxurpoia/bchess_48fa1207e7714a428373c65565e6524c/build/lc0-0.27.0
2021-07-03T08:07:52,975   Build dir: /tmp/pip-wheel-oxurpoia/bchess_48fa1207e7714a428373c65565e6524c/build/lc0-0.27.0/build/minsize
2021-07-03T08:07:52,975   Build type: native build
2021-07-03T08:07:52,975   Project name: lc0
2021-07-03T08:07:52,975   Project version: undefined
2021-07-03T08:07:52,975   C++ compiler for the host machine: c++ (gcc 8.3.0 "c++ (Raspbian 8.3.0-6+rpi1) 8.3.0")
2021-07-03T08:07:52,975   C++ linker for the host machine: c++ ld.bfd 2.31.1
2021-07-03T08:07:52,976   Host machine cpu family: arm
2021-07-03T08:07:52,976   Host machine cpu: armv7l
2021-07-03T08:07:52,976   Has header "optional" : YES
2021-07-03T08:07:52,976   Has header "string_view" : YES
2021-07-03T08:07:52,976   Has header "charconv" : YES
2021-07-03T08:07:52,976   Program scripts/compile_proto.py found: YES (/tmp/pip-wheel-oxurpoia/bchess_48fa1207e7714a428373c65565e6524c/build/lc0-0.27.0/scripts/compile_proto.py)
2021-07-03T08:07:52,977   Program git found: YES (/usr/bin/git)
2021-07-03T08:07:52,977   Message: cloning lczero-common.git into libs/lczero-common

2021-07-03T08:07:52,977   meson.build:93:0: ERROR: File libs/lczero-common/proto/net.proto does not exist.

2021-07-03T08:07:52,977   A full log can be found at /tmp/pip-wheel-oxurpoia/bchess_48fa1207e7714a428373c65565e6524c/build/lc0-0.27.0/build/minsize/meson-logs/meson-log.txt
2021-07-03T08:07:53,080   scons: *** [bchess/data/lc0] Error 1
2021-07-03T08:07:53,080   scons: building terminated because of errors.
2021-07-03T08:07:53,177   Building wheel for bchess (PEP 517): finished with status 'done'
2021-07-03T08:07:53,180   WARNING: Building wheel for bchess failed: [Errno 2] No such file or directory: '/tmp/pip-wheel-w07byvks/bchess-0.0.7-py3-none-manylinux_2_28_armv7l.whl'
2021-07-03T08:07:53,182 Failed to build bchess
2021-07-03T08:07:53,183 ERROR: Failed to build one or more wheels
2021-07-03T08:07:53,183 Exception information:
2021-07-03T08:07:53,183 Traceback (most recent call last):
2021-07-03T08:07:53,183   File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/base_command.py", line 180, in _main
2021-07-03T08:07:53,183     status = self.run(options, args)
2021-07-03T08:07:53,183   File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
2021-07-03T08:07:53,183     return func(self, options, args)
2021-07-03T08:07:53,183   File "/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/wheel.py", line 175, in run
2021-07-03T08:07:53,183     "Failed to build one or more wheels"
2021-07-03T08:07:53,183 pip._internal.exceptions.CommandError: Failed to build one or more wheels
2021-07-03T08:07:53,187 Removed build tracker: '/tmp/pip-req-tracker-9_6f9ssr'
```

**Comment by magv** [comment]
Thanks a lot, I see what's wrong now: the sdist archive still tries to download stuff during build (i.e. lzero-common), and you probably have that blocked (which makes sense). I'll try to fix it.
