### ISSUE TITLE
Missing package: gattlib

### ISSUE THREAD

**Issue by jabberwock** [piwheels/packages#231]
### Package name

gattlib

### Package version

0.20201113

### PyPI URL

https://pypi.org/project/gattlib/

### piwheels URL

https://www.piwheels.org/project/gattlib/

### Python version

- [x] Python 3.5
- [X] Python 3.7
- [x] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

This library does not build on a Raspberry Pi Zero W. Please see the following output:

**System information**

```
pi@porchy:~ $ uname -a && cat /proc/cpuinfo && echo && cat /etc/issue  # This is on a Raspberry Pi Zero W
Linux porchy 5.10.17+ #1414 Fri Apr 30 13:16:27 BST 2021 armv6l GNU/Linux
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 697.95
Features        : half thumb fastmult vfp edsp java tls 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2835
Revision        : 9000c1
Serial          : 00000000c407aa2b
Model           : Raspberry Pi Zero W Rev 1.1

Raspbian GNU/Linux 10 \n \l
````

**Command output**
```
pi@porchy:~ $ pip3 install gattlib -vv
Using pip 21.2.2 from /home/pi/.local/lib/python3.7/site-packages/pip (python 3.7)
Defaulting to user installation because normal site-packages is not writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-46fmnlhk
Created temporary directory: /tmp/pip-req-tracker-2tlpud2f
Initialized build tracking at /tmp/pip-req-tracker-2tlpud2f
Created build tracker: /tmp/pip-req-tracker-2tlpud2f
Entered build tracker: /tmp/pip-req-tracker-2tlpud2f
Created temporary directory: /tmp/pip-install-yn157wt8
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
2 location(s) to search for versions of gattlib:
* https://pypi.org/simple/gattlib/
* https://www.piwheels.org/simple/gattlib/
Fetching project page and analyzing links: https://pypi.org/simple/gattlib/
Getting page https://pypi.org/simple/gattlib/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/gattlib/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/gattlib/ HTTP/1.1" 304 0
  Found link https://files.pythonhosted.org/packages/7c/8f/861dbcc3da19f8324f5e0ac6940a2df682d2108d43d5fc734403be1c787a/gattlib-0.20150119.linux-x86_64.tar.gz#sha256=efe7d3133549c9f708317da5da1f388acf74c4f57221d5385f40828203f54e3d (from https://pypi.org/simple/gattlib/), version: 0.20150119.linux-x86_64
  Found link https://files.pythonhosted.org/packages/e1/b7/b8ef5aa35b93dc013a18918dafc1da50df7a1c0cdb43710224e71a7a060c/gattlib-0.20150119.tar.gz#sha256=73f4a8255c467f5010e042c33f1c06481ebe1d8fa41a6b556ca5061a31d988bc (from https://pypi.org/simple/gattlib/), version: 0.20150119
  Found link https://files.pythonhosted.org/packages/43/de/2ae25758e14447c2195b3628a5a5b50451977e39ac5196c53ece2d58784c/gattlib-0.20150130.tar.gz#sha256=a24157e5a32f4b37ef206d09c083e54cff1f05efadee8cea0da3446f256f7626 (from https://pypi.org/simple/gattlib/), version: 0.20150130
  Found link https://files.pythonhosted.org/packages/de/b9/6aa639cefedae3f81f79261ad8dfc4fe7c8f0c98a4434b2b4edda89040f6/gattlib-0.20150131.tar.gz#sha256=9d574eaa9688978a3e920085c4adf2e66b832eaa81ce5cf21ef90b668f53794d (from https://pypi.org/simple/gattlib/), version: 0.20150131
  Found link https://files.pythonhosted.org/packages/be/2f/5b1aecec551b42b59d8b399ad444b5672972efb590ca83d784dbe616a3e1/gattlib-0.20150805.tar.gz#sha256=7f5fbc1613a0225f2af79683ca907fed40b765369c61cf90d023cbf4a92bdb0c (from https://pypi.org/simple/gattlib/), version: 0.20150805
  Found link https://files.pythonhosted.org/packages/b7/5b/e0a8e4b2841fd0a34641e16bae5e3d8107073c2c21da4ae0a59a5150eb57/gattlib-0.20200117.post2.tar.gz#sha256=e3bd816c0a967f36e0d5d163472d2f4ca331b5057907f2a27a497258508736b9 (from https://pypi.org/simple/gattlib/), version: 0.20200117.post2
  Found link https://files.pythonhosted.org/packages/2a/53/aa2a12348549cd458bb196370b34415d9626a0e0bf3b5307e1d54c927640/gattlib-0.20200117.post3.tar.gz#sha256=0143d832927a11b20a843566d5cf34c68d9b1dd9041aa938a79395da0138f0e9 (from https://pypi.org/simple/gattlib/), version: 0.20200117.post3
  Found link https://files.pythonhosted.org/packages/04/df/9c6346358a2131a38cb4eec81d28ede43fa7895945c842e1d249722c94f7/gattlib-0.20200121.tar.gz#sha256=113952645c8bfbc3178726e58a35d3b799592913c522b7942c6f70812828b23f (from https://pypi.org/simple/gattlib/), version: 0.20200121
  Found link https://files.pythonhosted.org/packages/b1/d8/03cc2843e7235b7d2f55af7b3abec3cb94e14c0036dde10b505b6fe55f35/gattlib-0.20200122.tar.gz#sha256=e7bc9f073cd32d9259cfb7e5b12c76f45e29316259d1d9a7872333bc63cb3bbd (from https://pypi.org/simple/gattlib/), version: 0.20200122
  Found link https://files.pythonhosted.org/packages/58/a8/db457e638dfe6859a896f5ab58ab7a58d6c3301077680831c3bd4c9448cf/gattlib-0.20200911.post2.tar.gz#sha256=ed7f0156e14a181b541ebe71d07b82e964b3ef5f59e95ec6a91b0745ed6cbd59 (from https://pypi.org/simple/gattlib/), version: 0.20200911.post2
  Found link https://files.pythonhosted.org/packages/83/9c/a17f77a07cc0f84260676ea2cfeb631853b2887632fde9011c849a079248/gattlib-0.20200914.tar.gz#sha256=5afba2c7726927c669dc80d7582efa7a0d864941b48a28d1b51ea63e1828a6fb (from https://pypi.org/simple/gattlib/), version: 0.20200914
  Found link https://files.pythonhosted.org/packages/a5/a2/05dfc9e9d120146878a3ecdc93d4f1356e36937deed8cc19bc65a2f7a3d1/gattlib-0.20200915.tar.gz#sha256=373de4158b59653fe49a1ad14d9114e717ea2097568046740404dedee399e0ca (from https://pypi.org/simple/gattlib/), version: 0.20200915
  Found link https://files.pythonhosted.org/packages/6b/c0/81ee4d8624829ee503483ae7b76aeb168d23a58ee4c26b01b73e74180a67/gattlib-0.20200925.tar.gz#sha256=40601d0aa6097548204ba88547a0517e9d55ef20eff3347da6daea8572f9a8dd (from https://pypi.org/simple/gattlib/), version: 0.20200925
  Found link https://files.pythonhosted.org/packages/f6/c1/b6881eca018aa901f69dcb53077f7db58c798cbfc829394ac187e0e38bc6/gattlib-0.20200929.tar.gz#sha256=a7b3602e229645ffe5a4a27c77cf4fbd09bdd0f12afbadf7fcbfcb5ff4a3ea62 (from https://pypi.org/simple/gattlib/), version: 0.20200929
  Found link https://files.pythonhosted.org/packages/fe/8d/72d539dd6be2d9677864a1604b8db80696c2d5f018cf8093bf442311162f/gattlib-0.20201113.tar.gz#sha256=1e3d92d07bdaad7574aabc3fd36aea5ef1fae4339e521a162fe2341a9a33fcb5 (from https://pypi.org/simple/gattlib/), version: 0.20201113
Fetching project page and analyzing links: https://www.piwheels.org/simple/gattlib/
Getting page https://www.piwheels.org/simple/gattlib/
Found index url https://www.piwheels.org/simple
Looking up "https://www.piwheels.org/simple/gattlib/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): www.piwheels.org:443
https://www.piwheels.org:443 "GET /simple/gattlib/ HTTP/1.1" 200 107
Updating cache with response from "https://www.piwheels.org/simple/gattlib/"
Caching due to etag
Skipping link: not a file: https://www.piwheels.org/simple/gattlib/
Skipping link: not a file: https://pypi.org/simple/gattlib/
Given no hashes to check 14 links for project 'gattlib': discarding no candidates
Collecting gattlib
  Created temporary directory: /tmp/pip-unpack-a559ewmy
  Looking up "https://files.pythonhosted.org/packages/fe/8d/72d539dd6be2d9677864a1604b8db80696c2d5f018cf8093bf442311162f/gattlib-0.20201113.tar.gz" in the cache
  Current age based on date: 154565
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 154565
  Using cached gattlib-0.20201113.tar.gz (50 kB)
  Added gattlib from https://files.pythonhosted.org/packages/fe/8d/72d539dd6be2d9677864a1604b8db80696c2d5f018cf8093bf442311162f/gattlib-0.20201113.tar.gz#sha256=1e3d92d07bdaad7574aabc3fd36aea5ef1fae4339e521a162fe2341a9a33fcb5 to build tracker '/tmp/pip-req-tracker-2tlpud2f'
    Running setup.py (path:/tmp/pip-install-yn157wt8/gattlib_3a74c7167f6448b28b3bf65ac404785b/setup.py) egg_info for package gattlib
    Created temporary directory: /tmp/pip-pip-egg-info-tluh0qzy
    Running command python setup.py egg_info
    running egg_info
    creating /tmp/pip-pip-egg-info-tluh0qzy/gattlib.egg-info
    writing /tmp/pip-pip-egg-info-tluh0qzy/gattlib.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-tluh0qzy/gattlib.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-tluh0qzy/gattlib.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-tluh0qzy/gattlib.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-tluh0qzy/gattlib.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file '/tmp/pip-pip-egg-info-tluh0qzy/gattlib.egg-info/SOURCES.txt'
  Source in /tmp/pip-install-yn157wt8/gattlib_3a74c7167f6448b28b3bf65ac404785b has version 0.20201113, which satisfies requirement gattlib from https://files.pythonhosted.org/packages/fe/8d/72d539dd6be2d9677864a1604b8db80696c2d5f018cf8093bf442311162f/gattlib-0.20201113.tar.gz#sha256=1e3d92d07bdaad7574aabc3fd36aea5ef1fae4339e521a162fe2341a9a33fcb5
  Removed gattlib from https://files.pythonhosted.org/packages/fe/8d/72d539dd6be2d9677864a1604b8db80696c2d5f018cf8093bf442311162f/gattlib-0.20201113.tar.gz#sha256=1e3d92d07bdaad7574aabc3fd36aea5ef1fae4339e521a162fe2341a9a33fcb5 from build tracker '/tmp/pip-req-tracker-2tlpud2f'
Created temporary directory: /tmp/pip-unpack-veb3vdoc
Building wheels for collected packages: gattlib
  Created temporary directory: /tmp/pip-wheel-6gtxa3bj
  Building wheel for gattlib (setup.py) ...   Destination directory: /tmp/pip-wheel-6gtxa3bj
  Running command /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yn157wt8/gattlib_3a74c7167f6448b28b3bf65ac404785b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yn157wt8/gattlib_3a74c7167f6448b28b3bf65ac404785b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-6gtxa3bj
  running bdist_wheel
  running build
  running build_ext
  building 'gattlib' extension
  creating build
  creating build/temp.linux-armv6l-3.7
  creating build/temp.linux-armv6l-3.7/src
  creating build/temp.linux-armv6l-3.7/src/bluez
  creating build/temp.linux-armv6l-3.7/src/bluez/lib
  creating build/temp.linux-armv6l-3.7/src/bluez/attrib
  creating build/temp.linux-armv6l-3.7/src/bluez/src
  creating build/temp.linux-armv6l-3.7/src/bluez/src/shared
  creating build/temp.linux-armv6l-3.7/src/bluez/btio
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DVERSION="5.25" -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -Isrc/bluez -I/usr/include/python3.7m -c src/gattservices.cpp -o build/temp.linux-armv6l-3.7/src/gattservices.o
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DVERSION="5.25" -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -Isrc/bluez -I/usr/include/python3.7m -c src/beacon.cpp -o build/temp.linux-armv6l-3.7/src/beacon.o
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DVERSION="5.25" -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -Isrc/bluez -I/usr/include/python3.7m -c src/bindings.cpp -o build/temp.linux-armv6l-3.7/src/bindings.o
  arm-linux-gnueabihf-gcc: fatal error: Killed signal terminated program cc1plus
  compilation terminated.
  error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
error
  ERROR: Failed building wheel for gattlib
  Running setup.py clean for gattlib
  Running command /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yn157wt8/gattlib_3a74c7167f6448b28b3bf65ac404785b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yn157wt8/gattlib_3a74c7167f6448b28b3bf65ac404785b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
  running clean
  removing 'build/temp.linux-armv6l-3.7' (and everything under it)
  'build/lib.linux-armv6l-3.7' does not exist -- can't clean it
  'build/bdist.linux-armv6l' does not exist -- can't clean it
  'build/scripts-3.7' does not exist -- can't clean it
  removing 'build'
Failed to build gattlib
Installing collected packages: gattlib
  Created temporary directory: /tmp/pip-record-vx6cft5i
    Running command /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yn157wt8/gattlib_3a74c7167f6448b28b3bf65ac404785b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yn157wt8/gattlib_3a74c7167f6448b28b3bf65ac404785b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-vx6cft5i/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/pi/.local/include/python3.7m/gattlib
    running install
    running build
    running build_ext
    building 'gattlib' extension
    creating build
    creating build/temp.linux-armv6l-3.7
    creating build/temp.linux-armv6l-3.7/src
    creating build/temp.linux-armv6l-3.7/src/bluez
    creating build/temp.linux-armv6l-3.7/src/bluez/lib
    creating build/temp.linux-armv6l-3.7/src/bluez/attrib
    creating build/temp.linux-armv6l-3.7/src/bluez/src
    creating build/temp.linux-armv6l-3.7/src/bluez/src/shared
    creating build/temp.linux-armv6l-3.7/src/bluez/btio
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DVERSION="5.25" -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -Isrc/bluez -I/usr/include/python3.7m -c src/gattservices.cpp -o build/temp.linux-armv6l-3.7/src/gattservices.o
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DVERSION="5.25" -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -Isrc/bluez -I/usr/include/python3.7m -c src/beacon.cpp -o build/temp.linux-armv6l-3.7/src/beacon.o
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DVERSION="5.25" -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -Isrc/bluez -I/usr/include/python3.7m -c src/bindings.cpp -o build/temp.linux-armv6l-3.7/src/bindings.o
    arm-linux-gnueabihf-gcc: fatal error: Killed signal terminated program cc1plus
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    Running setup.py install for gattlib ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yn157wt8/gattlib_3a74c7167f6448b28b3bf65ac404785b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yn157wt8/gattlib_3a74c7167f6448b28b3bf65ac404785b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-vx6cft5i/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/pi/.local/include/python3.7m/gattlib Check the logs for full command output.         
Exception information:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 796, in install
    req_description=str(self.req),
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/operations/install/legacy.py", line 121, in install
    raise LegacyInstallFailure
pip._internal.operations.install.legacy.LegacyInstallFailure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 399, in run
    pycompile=options.compile,
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 81, in install_given_reqs
    pycompile=pycompile,
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 800, in install
    six.reraise(*exc.parent)
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_vendor/six.py", line 719, in reraise
    raise value
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/operations/install/legacy.py", line 111, in install
    cwd=unpacked_source_directory,
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 278, in runner
    spinner=spinner,
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 244, in call_subprocess
    raise InstallationSubprocessError(proc.returncode, command_desc)
pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yn157wt8/gattlib_3a74c7167f6448b28b3bf65ac404785b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yn157wt8/gattlib_3a74c7167f6448b28b3bf65ac404785b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-vx6cft5i/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/pi/.local/include/python3.7m/gattlib Check the logs for full command output.
Removed build tracker: '/tmp/pip-req-tracker-2tlpud2f'
pi@porchy:~ $ 
```

**Comment by bennuttall** [comment]
This looks like an issue with the metadata in `setup.py` - best to take it up with the maintainers
