### ISSUE TITLE
Missing package: fluvio

### ISSUE THREAD

**Issue by morenol** [piwheels/packages#244]
### Package name

fluvio

### Package version

all

### PyPI URL

https://pypi.org/project/fluvio/

### piwheels URL

https://www.piwheels.org/project/fluvio/

### Python version

- [X] Python 3.5
- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [X] Yes

**Comment by bennuttall** [comment]
```
2021-09-19T03:35:31,400   error: failed to parse manifest at `/home/piwheels/.cargo/registry/src/github.com-1285ae84e5963aae/fluvio-spu-schema-0.8.1/Cargo.toml`
2021-09-19T03:35:31,401   Caused by:
2021-09-19T03:35:31,401     feature `resolver` is required
2021-09-19T03:35:31,401     consider adding `cargo-features = ["resolver"]` to the manifest
```

Build output: http://paste.debian.net/1212411/

**Comment by MichaIng** [comment]
Latest release compiled successfully. Only on Trixie it ran into missing free disk (or `/tmp`=`tmpfs`=) space:
```
2025-09-15T19:15:11,659   Fetching project page and analyzing links: https://www.piwheels.org/simple/wheel/
2025-09-15T19:15:11,659   Getting page https://www.piwheels.org/simple/wheel/
2025-09-15T19:15:11,659   Found index url https://www.piwheels.org/simple/
2025-09-15T19:15:11,659   Looking up "https://www.piwheels.org/simple/wheel/" in the cache
2025-09-15T19:15:11,660   Request header has "max_age" as 0, cache bypassed
2025-09-15T19:15:11,660   https://www.piwheels.org:443 "GET /simple/wheel/ HTTP/1.1" 200 4210
2025-09-15T19:15:11,660   ERROR: Could not install packages due to an OSError.
2025-09-15T19:15:11,660   Traceback (most recent call last):
2025-09-15T19:15:11,660     File "/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
2025-09-15T19:15:11,661       yield
2025-09-15T19:15:11,661     File "/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py", line 561, in read
2025-09-15T19:15:11,661       data = self._fp_read(amt) if not fp_closed else b""
2025-09-15T19:15:11,661              ~~~~~~~~~~~~~^^^^^
2025-09-15T19:15:11,661     File "/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
2025-09-15T19:15:11,661       return self._fp.read(amt) if amt is not None else self._fp.read()
2025-09-15T19:15:11,661              ~~~~~~~~~~~~~^^^^^
2025-09-15T19:15:11,661     File "/usr/lib/python3/dist-packages/pip/_vendor/cachecontrol/filewrapper.py", line 102, in read
2025-09-15T19:15:11,662       self.__buf.write(data)
2025-09-15T19:15:11,662       ~~~~~~~~~~~~~~~~^^^^^^
2025-09-15T19:15:11,662     File "/usr/lib/python3.13/tempfile.py", line 690, in func_wrapper
2025-09-15T19:15:11,662       return func(*args, **kwargs)
2025-09-15T19:15:11,662   OSError: [Errno 28] No space left on device
```
I guess some quirk with the large backlog that was caught up, and triggering that again works.

**Comment by bennuttall** [comment]
Queued for rebuild

**Comment by MichaIng** [comment]
Latest wheels are available for all Python versions. Closing this.
