### ISSUE TITLE
Missing package: clang-format

### ISSUE THREAD

**Issue by nightlark** [piwheels/packages#248]
### Package name

clang-format

### Package version

all

### PyPI URL

https://pypi.org/project/clang-format/

### piwheels URL

https://www.piwheels.org/project/clang-format/

### Python version

- [X] Python 3.5
- [x] Python 3.7
- [x] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

I'm trying to figure out why the build failed -- did it reach a timeout or was their a failure earlier in the process such as getting the source code or a compiler error?

**Comment by bennuttall** [comment]
It failed on cp35m because of the use of f-strings which require Python 3.6. It hasn't been attempted on cp37m or cp39 yet, as there was something blocking the queue. I've just unblocked it so it should be attempted soon.

**Comment by bennuttall** [comment]
It's now failed on the others due to the project trying to run a "git clone" which isn't permitted in piwheels.

**Comment by nightlark** [comment]
Thanks! It seems the time taken to fetch and extract a source tarball would also be good for faster builds... 4x faster than a shallow clone, and minutes faster than the current git clone.

**Comment by nightlark** [comment]
Is it possible to get a build run triggered (for Python 3.7 or 3.9) using the sdist published on TestPyPI https://test.pypi.org/project/clang-format/13.0.0/?

Or are there instructions for locally replicating the build environment to see if it will work on the next PyPI release?

**Comment by bennuttall** [comment]
Like I said, "git clone" is not permitted in piwheels, that's the problem. You can't run "git clone" in your setup script.

**Comment by nightlark** [comment]
> Like I said, "git clone" is not permitted in piwheels, that's the problem. You can't run "git clone" in your setup script.

Yes, I know... unfortunately the maintainer didn't get the change merged until after already publishing a 13.0.0 release on PyPI, however he did publish an sdist with the change to TestPyPI, hence the question about getting a test build triggered based on the TestPyPI sdist or replicating the build environment on a local rPi.

The maintainer said he doesn't really want to publish a patch release because then the package version number will no longer match up with the `clang-format` version being packaged -- clang-format only releases a new version every 3-6 months, which is a very long iteration time to find out if there are any other issues building the wheel now that the git clone has been removed.

**Comment by MichaIng** [comment]
The latest version does not support Debian Bullseye anymore, since its CMake is too old. The Python 3.13 build was skipped/has no log, and the Python 3.11 build fails at the final stage when making the wheel:
```
2026-03-13T07:09:40,345   *** Making wheel...
2026-03-13T07:09:40,386   2026-03-13 07:09:40,385 - scikit_build_core - DEBUG - Including file clang_format/__init__.py because it exists (and isn't matched any other way).
2026-03-13T07:10:38,039   Traceback (most recent call last):
2026-03-13T07:10:38,039     File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
2026-03-13T07:10:38,042       main()
2026-03-13T07:10:38,043     File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
2026-03-13T07:10:38,044       json_out['return_val'] = hook(**hook_input['kwargs'])
2026-03-13T07:10:38,045                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2026-03-13T07:10:38,045     File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
2026-03-13T07:10:38,046       return _build_backend().build_wheel(wheel_directory, config_settings,
2026-03-13T07:10:38,047              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2026-03-13T07:10:38,048     File "/tmp/pip-build-env-waakxy26/overlay/local/lib/python3.11/dist-packages/scikit_build_core/build/__init__.py", line 33, in build_wheel
2026-03-13T07:10:38,049       return _build_wheel_impl(
2026-03-13T07:10:38,051              ^^^^^^^^^^^^^^^^^^
2026-03-13T07:10:38,052     File "/tmp/pip-build-env-waakxy26/overlay/local/lib/python3.11/dist-packages/scikit_build_core/build/wheel.py", line 177, in _build_wheel_impl
2026-03-13T07:10:38,056       return _build_wheel_impl_impl(
2026-03-13T07:10:38,057              ^^^^^^^^^^^^^^^^^^^^^^^
2026-03-13T07:10:38,058     File "/tmp/pip-build-env-waakxy26/overlay/local/lib/python3.11/dist-packages/scikit_build_core/build/wheel.py", line 276, in _build_wheel_impl_impl
2026-03-13T07:10:38,060       with tempfile.TemporaryDirectory() as tmpdir:
2026-03-13T07:10:38,061     File "/usr/lib/python3.11/tempfile.py", line 1052, in __exit__
2026-03-13T07:10:38,063       self.cleanup()
2026-03-13T07:10:38,065     File "/usr/lib/python3.11/tempfile.py", line 1056, in cleanup
2026-03-13T07:10:38,066       self._rmtree(self.name, ignore_errors=self._ignore_cleanup_errors)
2026-03-13T07:10:38,067     File "/usr/lib/python3.11/tempfile.py", line 1038, in _rmtree
2026-03-13T07:10:38,068       _rmtree(name, onerror=onerror)
2026-03-13T07:10:38,069     File "/usr/lib/python3.11/shutil.py", line 732, in rmtree
2026-03-13T07:10:38,070       _rmtree_safe_fd(fd, path, onerror)
2026-03-13T07:10:38,071     File "/usr/lib/python3.11/shutil.py", line 660, in _rmtree_safe_fd
2026-03-13T07:10:38,072       _rmtree_safe_fd(dirfd, fullname, onerror)
2026-03-13T07:10:38,073     File "/usr/lib/python3.11/shutil.py", line 660, in _rmtree_safe_fd
2026-03-13T07:10:38,074       _rmtree_safe_fd(dirfd, fullname, onerror)
2026-03-13T07:10:38,074     File "/usr/lib/python3.11/shutil.py", line 660, in _rmtree_safe_fd
2026-03-13T07:10:38,075       _rmtree_safe_fd(dirfd, fullname, onerror)
2026-03-13T07:10:38,076     File "/usr/lib/python3.11/shutil.py", line 683, in _rmtree_safe_fd
2026-03-13T07:10:38,077       onerror(os.unlink, fullname, sys.exc_info())
2026-03-13T07:10:38,078     File "/usr/lib/python3.11/shutil.py", line 681, in _rmtree_safe_fd
2026-03-13T07:10:38,079       os.unlink(entry.name, dir_fd=topfd)
2026-03-13T07:10:38,080   OSError: [Errno 16] Device or resource busy: '.nfs000000000012f9a300011866'
```
The same "device or resource busy" happened with the v21.1.8 Python 3.11 build, but the v22.1.0 build succeeded. It tries to remove the build directory, but the NFS drive reports it as still opened by another process 🤔.

**Comment by MichaIng** [comment]
The latest build succeeded for all Python versions. I missed that it is a single `py2.py3-none-linux` for all Python versions. And since it has no shared libraries linked, that should not cause any issues.

Hence marking this as closed.
