### ISSUE TITLE
Missing package: PyQt6

### ISSUE THREAD

**Issue by skpang** [piwheels/packages#297]
### Package name

pyqt6

### Package version

all

### PyPI URL

https://pypi.org/project/pyqt6/

### piwheels URL

https://www.piwheels.org/project/pyqt6/

### Python version

- [ ] Python 3.5
- [X] Python 3.7
- [ ] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

pyqt6 won't install.

pi@raspberrypi:~ $ sudo pip3 install pyqt6
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pyqt6
  Downloading https://files.pythonhosted.org/packages/45/d6/36df7171a4cb00580a608bd92ce085f05fff5e04a74eeac0c52d7de0a584/PyQt6-6.2.3.tar.gz (1.0MB)
    100% |████████████████████████████████| 1.0MB 416kB/s 
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-ycjjsaeo/pyqt6/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ycjjsaeo/pyqt6/

**Comment by MichaIng** [comment]
The latest version does not support Python 3.9 anymore, but Python 3.11 and 3.13 builds fail on metadata generation:
```
2026-01-08T17:45:19,319   ERROR: [present-rich] Preparing metadata (pyproject.toml) exited with 1
2026-01-08T17:45:19,332   [bold magenta]full command[/]: [blue]/usr/bin/python3 /usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp2m8o6zsa[/]
2026-01-08T17:45:19,332   [bold magenta]cwd[/]: /tmp/pip-wheel-q71c611j/pyqt6_0602064774b04e969ac9344cdb402c58
2026-01-08T17:45:19,333   Preparing metadata (pyproject.toml): finished with status 'error'
2026-01-08T17:45:19,335 ERROR: [present-rich] metadata generation failed
2026-01-08T17:45:19,341 Exception information:
2026-01-08T17:45:19,341 Traceback (most recent call last):
2026-01-08T17:45:19,341   File "/usr/lib/python3/dist-packages/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
2026-01-08T17:45:19,341     distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
2026-01-08T17:45:19,341                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2026-01-08T17:45:19,341   File "/usr/lib/python3/dist-packages/pip/_internal/utils/misc.py", line 746, in prepare_metadata_for_build_wheel
2026-01-08T17:45:19,341     return super().prepare_metadata_for_build_wheel(
2026-01-08T17:45:19,341            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2026-01-08T17:45:19,341   File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_impl.py", line 186, in prepare_metadata_for_build_wheel
2026-01-08T17:45:19,341     return self._call_hook('prepare_metadata_for_build_wheel', {
2026-01-08T17:45:19,341            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2026-01-08T17:45:19,341   File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_impl.py", line 311, in _call_hook
2026-01-08T17:45:19,341     self._subprocess_runner(
2026-01-08T17:45:19,341   File "/usr/lib/python3/dist-packages/pip/_internal/utils/subprocess.py", line 252, in runner
2026-01-08T17:45:19,341     call_subprocess(
2026-01-08T17:45:19,341   File "/usr/lib/python3/dist-packages/pip/_internal/utils/subprocess.py", line 224, in call_subprocess
2026-01-08T17:45:19,341     raise error
2026-01-08T17:45:19,341 pip._internal.exceptions.InstallationSubprocessError: Preparing metadata (pyproject.toml) exited with 1
```
Not sure what this means 🤔.
