### ISSUE TITLE
Missing package: grpcio

### ISSUE THREAD

**Issue by gnossen** [piwheels/packages#308]
### Package name

grpcio

### Package version

1.46+

### PyPI URL

https://pypi.org/project/grpcio/

### piwheels URL

https://www.piwheels.org/project/grpcio/

### Python version

- [X] Python 3.5
- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [X] Yes

### More information

It looks like the build has been failing since 1.46 with the following error:

```
2022-06-17T19:06:09,566 Collecting grpcio==1.47.0rc1
2022-06-17T19:06:09,571   Created temporary directory: /tmp/pip-unpack-1d9_gblt
2022-06-17T19:06:11,283   Downloading grpcio-1.47.0rc1.tar.gz (21.9 MB)
2022-06-17T19:06:39,255   Added grpcio==1.47.0rc1 from https://files.pythonhosted.org/packages/5e/69/bc30cb1e02a46110ce19589261eaabe5a09a58075e559b43b1c150cf3205/grpcio-1.47.0rc1.tar.gz#sha256=2548a7adca9db022f9a516d36d29d214a58a6dbde9bc29f54ee4198f7a3899bd to build tracker '/tmp/pip-build-tracker-jpzsr1ep'
2022-06-17T19:06:39,258   Running setup.py (path:/tmp/pip-wheel-ev5792q7/grpcio_b673f59ba3e0437bb1ff93e5d678be19/setup.py) egg_info for package grpcio
2022-06-17T19:06:39,260   Created temporary directory: /tmp/pip-pip-egg-info-3f8_6uur
2022-06-17T19:06:39,260   Preparing metadata (setup.py): started
2022-06-17T19:06:39,262   Running command python setup.py egg_info
2022-06-17T19:06:44,306   Traceback (most recent call last):
2022-06-17T19:06:44,308     File "<string>", line 36, in <module>
2022-06-17T19:06:44,308     File "<pip-setuptools-caller>", line 34, in <module>
2022-06-17T19:06:44,308     File "/tmp/pip-wheel-ev5792q7/grpcio_b673f59ba3e0437bb1ff93e5d678be19/setup.py", line 263, in <module>
2022-06-17T19:06:44,309       if check_linker_need_libatomic():
2022-06-17T19:06:44,309     File "/tmp/pip-wheel-ev5792q7/grpcio_b673f59ba3e0437bb1ff93e5d678be19/setup.py", line 223, in check_linker_need_libatomic
2022-06-17T19:06:44,309       stderr=PIPE)
2022-06-17T19:06:44,310     File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
2022-06-17T19:06:44,310       restore_signals, start_new_session)
2022-06-17T19:06:44,310     File "/usr/lib/python3.7/subprocess.py", line 1436, in _execute_child
2022-06-17T19:06:44,311       executable = os.fsencode(executable)
2022-06-17T19:06:44,311     File "/usr/lib/python3.7/os.py", line 809, in fsencode
2022-06-17T19:06:44,311       filename = fspath(filename)  # Does type-checking of `filename`.
2022-06-17T19:06:44,312   TypeError: expected str, bytes or os.PathLike object, not list
```

This suggests that there is an issue somewhere around [here](https://github.com/grpc/grpc/blob/1630efd8ab3d2ff4b006f1288fde1be5c29dc651/setup.py#L210). It's not clear to me how the filename being encountered by `fsencode` is a list. I think I would need access to your CI environment to figure that out. Our distribtests are not currently encountering this issue, so I suspect there is some sort of difference between our environments. Perhaps something odd about the `CXX` env var?

**Comment by fedej** [comment]
I believe the problem is in setup.py as mentioned [here](https://github.com/grpc/grpc/pull/30076)

**Comment by bennuttall** [comment]
Looks like this is resolved now, the newer versions are building successfully :+1:
