### ISSUE TITLE
install error: bandl

### ISSUE THREAD

**Issue by sudheer628** [piwheels/packages#318]
### Package name

bandl

### Package version

0.1.0

### PyPI URL

https://pypi.org/project/bandl/

### piwheels URL

https://www.piwheels.org/project/bandl/

### Python version

- [ ] Python 3.5
- [ ] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

bandl install failed -- please suggest

Processing c:\users\sai-s\documents\finvasia\bandl-0.1.0-py3-none-any.whl
Requirement already satisfied: requests in c:\users\sai-s\appdata\local\programs\python\python39\lib\site-packages (from bandl==0.1.0) (2.28.1)
Requirement already satisfied: openpyxl in c:\users\sai-s\appdata\roaming\python\python39\site-packages (from bandl==0.1.0) (3.0.10)
Collecting datetime
  Downloading DateTime-4.5-py2.py3-none-any.whl (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB ? eta 0:00:00
Collecting futures
  Using cached futures-3.0.5.tar.gz (25 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "C:\Users\sai-s\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\__init__.py", line 247, in <module>
          monkey.patch_all()
        File "C:\Users\sai-s\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\monkey.py", line 99, in patch_all
          patch_for_msvc_specialized_compiler()
        File "C:\Users\sai-s\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\monkey.py", line 159, in patch_for_msvc_specialized_compiler
          patch_func(*msvc14('_get_vc_env'))
        File "C:\Users\sai-s\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\monkey.py", line 149, in patch_params
          mod = import_module(mod_name)
        File "C:\Users\sai-s\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module        
          return _bootstrap._gcd_import(name[level:], package, level)
        File "C:\Users\sai-s\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 20, in <module>
          import unittest.mock as mock
        File "C:\Users\sai-s\AppData\Local\Programs\Python\Python39\lib\unittest\mock.py", line 26, in <module>
          import asyncio
        File "C:\Users\sai-s\AppData\Local\Programs\Python\Python39\lib\asyncio\__init__.py", line 8, in <module>
          from .base_events import *
        File "C:\Users\sai-s\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 18, in <module>
          import concurrent.futures
        File "C:\Users\sai-s\AppData\Local\Temp\pip-install-trwzps75\futures_4e94b002b3714add8912d31e5a82f813\concurrent\futures\__init__.py", line 8, in <module>
          from concurrent.futures._base import (FIRST_COMPLETED,
        File "C:\Users\sai-s\AppData\Local\Temp\pip-install-trwzps75\futures_4e94b002b3714add8912d31e5a82f813\concurrent\futures\_base.py", line 357
          raise type(self._exception), self._exception, self._traceback
                                     ^
      SyntaxError: invalid syntax
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by bennuttall** [comment]
You are reporting this error in the wrong place. This is the Raspberry Pi index called piwheels. You are using Windows.
