### ISSUE TITLE
Missing package: boost-histogram

### ISSUE THREAD

**Issue by matthewfeickert** [piwheels/packages#341]
### Package name

boost-histogram

### Package version

all

### PyPI URL

https://pypi.org/project/boost-histogram/

### piwheels URL

https://www.piwheels.org/project/boost-histogram/

### Python version

- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

I'm not a maintainer of [boost-histogram](https://github.com/scikit-hep/boost-histogram) but I am a member of the Scikit-HEP admin team (`boost-histogram` is a Scikit-HEP project). `boost-histogram` powers a lot of functionality in the Scikit-HEP ecosystem, so it would be quite nice if support could be added to compliment the nice support for [`awkward`](https://www.piwheels.org/project/awkward/).

**Comment by bennuttall** [comment]
We had to skip this package as it was repeatedly hitting the 3 hour timeout and blocking anything else from being built. We can try again, perhaps just the latest version, if you think it should build ok.

Have you tried building it on a Pi? Is there anything special that's needed? We can install apt packages as required.

If it requires Rust, then it'll have to wait for the work on rustup to be completed https://github.com/piwheels/piwheels/pull/328

**Comment by matthewfeickert** [comment]
> Have you tried building it on a Pi? Is there anything special that's needed? We can install apt packages as required.

I haven't yet, but I can try myself later.
 
> If it requires Rust, then it'll have to wait for the work on rustup to be completed [piwheels/piwheels#328](https://github.com/piwheels/piwheels/pull/328)

There's no Rust to my knowledge. Just C++ and pybind11.

**Comment by matthewfeickert** [comment]
I was able to pretty quickly build a sdist (no surprise there) and a wheel for `boost-histogram` `v1.3.2` on my Raspberry Pi 4 Model B running Raspbian 11 bullseye

```console
$ uname -a
Linux raspberrypi 5.15.84-v7l+ #1613 SMP Thu Jan 5 12:01:26 GMT 2023 armv7l GNU/Linux
```

with the following

```console
$ python -m venv build && . build/bin/activate
$ python -m pip install --upgrade pip setuptools wheel
$ python -m pip install build
$ git clone --recursive --branch v1.3.2 https://github.com/scikit-hep/boost-histogram.git
$ cd boost-histogram/
$ python -m build .
...
Successfully built boost_histogram-1.3.2.tar.gz and boost_histogram-1.3.2-cp39-cp39-linux_armv7l.whl
```

I tried to test the wheel by installing and getting it to pass pytest, but it fails at import

```console
$ python -m pip install ./dist/boost_histogram-1.3.2-cp39-cp39-linux_armv7l.whl
$ python -m pip install pytest pytest-benchmark
$ python -c 'import boost_histogram'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pi/.local/venvs/build/lib/python3.9/site-packages/boost_histogram/__init__.py", line 1, in <module>
    from . import accumulators, axis, numpy, storage
  File "/home/pi/.local/venvs/build/lib/python3.9/site-packages/boost_histogram/accumulators.py", line 1, in <module>
    from ._core.accumulators import (  # pylint: disable=import-error
ImportError: /home/pi/.local/venvs/build/lib/python3.9/site-packages/boost_histogram/_core.cpython-39-arm-linux-gnueabihf.so: undefined symbol: __atomic_load_8
```

From a quick glance at the Issues it seems that this `undefined symbol: __atomic_load_8` is something that people have seen before, but I'm not experienced enough to know what this means without doing some looking (which I don't have time to do right right now).

If it is of interest, here's the wheel that I built (I've appended the `.zip` to the end so that GitHub will recognize it as a zip file and let me upload it): [boost_histogram-1.3.2-cp39-cp39-linux_armv7l.whl.zip](https://github.com/piwheels/packages/files/10385774/boost_histogram-1.3.2-cp39-cp39-linux_armv7l.whl.zip)

(I don't think he'll have time to comment, but cc @henryiii &mdash; one of the maintainers.)

**Comment by henryiii** [comment]
> 3 hour timeout

It shouldn't take 3 hours to build! I can build in under a minute on my MacBook; a more normal computer still usually can do it in 5-10 mins. Maybe you are running out of memory and using the swap - I'd try forcing the build to run on a single core via setting CMAKE_BUILD_PARALLEL_LEVEL to 1 (or maybe 2 if that works). You don't need to run all the tests, just a couple of tests (maybe as simple as importing it) should be fine, maybe that would help?

**Comment by henryiii** [comment]
Yes, that's about what I'd expect, so I'm guessing maybe the memory on the build nodes is really low and multhreaded building is filling it, causing this to take much longer multithreaded.

I think we needs `-latomic` injected for ARM. Currently it's using setuptools (ignore the CMAKE in the variable above!), so we can manually add it if we detect an armv7 platform, perhaps?

**Comment by matthewfeickert** [comment]
> I think we needs `-latomic` injected for ARM. Currently it's using setuptools (ignore the CMAKE in the variable above!), so we can manually add it if we detect an armv7 platform, perhaps? For now, I think setting LDFLAGS would be easiest.

I attempted this with the following patch

```diff
$ git diff v1.3.2
diff --git a/setup.py b/setup.py
index 308dbb1..b2a2768 100644
--- a/setup.py
+++ b/setup.py
@@ -1,6 +1,7 @@
 import os
 import sys
 from pathlib import Path
+import platform
 
 from setuptools import setup
 
@@ -38,6 +39,13 @@ INCLUDE_DIRS = [
     "extern/variant2/include",
 ]
 
+if sys.platform.startswith("win32"):
+    extra_compile_args=["/d2FH4-"]
+elif platform.machine() == "armv7l":
+    extra_compile_args=["-latomic"]
+else:
+    extra_compile_args=[]
+
 ext_modules = [
     Pybind11Extension(
         "boost_histogram._core",
@@ -45,7 +53,7 @@ ext_modules = [
         include_dirs=INCLUDE_DIRS,
         cxx_std=cxx_std,
         include_pybind11=False,
-        extra_compile_args=["/d2FH4-"] if sys.platform.startswith("win32") else [],
+        extra_compile_args=extra_compile_args,
     )
 ]

```

but unless I'm doing something wrong (very possible) this still fails with

```pytb
$ python -c 'import boost_histogram'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pi/.local/venvs/build/lib/python3.9/site-packages/boost_histogram/__init__.py", line 1, in <module>
    from . import accumulators, axis, numpy, storage
  File "/home/pi/.local/venvs/build/lib/python3.9/site-packages/boost_histogram/accumulators.py", line 1, in <module>
    from ._core.accumulators import (  # pylint: disable=import-error
ImportError: /home/pi/.local/venvs/build/lib/python3.9/site-packages/boost_histogram/_core.cpython-39-arm-linux-gnueabihf.so: undefined symbol: __atomic_load_8
```

**Comment by henryiii** [comment]
That's a link arg, not a compile arg. Try:

```
LDFLAGS="-latomic" python -m build .
```

**Comment by matthewfeickert** [comment]
> That's a link arg, not a compile arg.

Whoops! Sorry I seem to be asleep at the keyboard today &mdash; can't get much more obvious than that.

> Try:
> 
> ```
> LDFLAGS="-latomic" python -m build .
> ```

Still failing though

```console
$ LDFLAGS="-latomic" python -m build .
...
Successfully built boost_histogram-1.3.2.tar.gz and boost_histogram-1.3.2-cp39-cp39-linux_armv7l.whl
$ python -m pip uninstall -y boost-histogram
$ python -m pip install ./dist/boost_histogram*.whl
$ python -c 'import boost_histogram'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pi/.local/venvs/build/lib/python3.9/site-packages/boost_histogram/__init__.py", line 1, in <module>
    from . import accumulators, axis, numpy, storage
  File "/home/pi/.local/venvs/build/lib/python3.9/site-packages/boost_histogram/accumulators.py", line 1, in <module>
    from ._core.accumulators import (  # pylint: disable=import-error
ImportError: /home/pi/.local/venvs/build/lib/python3.9/site-packages/boost_histogram/_core.cpython-39-arm-linux-gnueabihf.so: undefined symbol: __atomic_load_8
```

**Comment by matthewfeickert** [comment]
The following patch works though

```diff
 git diff v1.3.2
diff --git a/setup.py b/setup.py
index 308dbb1..caf5237 100644
--- a/setup.py
+++ b/setup.py
@@ -1,6 +1,7 @@
 import os
 import sys
 from pathlib import Path
+import platform
 
 from setuptools import setup
 
@@ -46,6 +47,7 @@ ext_modules = [
         cxx_std=cxx_std,
         include_pybind11=False,
         extra_compile_args=["/d2FH4-"] if sys.platform.startswith("win32") else [],
+        extra_link_args=["-latomic"] if platform.machine() == "armv7l" else [],
     )
 ]
 
```

```console
$ python -m build .
...
Successfully built boost_histogram-1.3.3.dev0+g0c8659c.d20230110.tar.gz and boost_histogram-1.3.3.dev0+g0c8659c.d20230110-cp39-cp39-linux_armv7l.whl
$ python -m pip uninstall -y boost-histogram
$ python -m pip install ./dist/boost_histogram*.whl
$ python -c 'import boost_histogram; print(boost_histogram)'
<module 'boost_histogram' from '/home/pi/.local/venvs/build/lib/python3.9/site-packages/boost_histogram/__init__.py'
```

**Comment by matthewfeickert** [comment]
> Is it possible to build from PyPI with just `pip3 wheel`? That's how our automated builds work. I'll try it when I get chance.

Not without the patch that I have above. I've opened https://github.com/scikit-hep/boost-histogram/issues/822 to discuss if this is worth supporting, or if the maintainers would prefer people to just move over to using a 64-bit OS on Raspberry Pi.

**Comment by henryiii** [comment]
`pip3 wheel` and `python -m build` are basically the same, with `python -m build` being preferred. Pip is slowly moving toward making build the backend for the `wheel` command (technically, I think they'd rather drop it, but too many people are using it because it predates build). It doesn't make any difference above, it's just that armv7 requires an extra non-standard link argument to use C++ atomics.

I don't know why `LDFLAGS` didn't work, it seems like it should here: https://setuptools.pypa.io/en/latest/userguide/ext_modules.html#compiler-and-linker-options

**Comment by matthewfeickert** [comment]
> I don't know why `LDFLAGS` didn't work, it seems like it should here: https://setuptools.pypa.io/en/latest/userguide/ext_modules.html#compiler-and-linker-options

I agree that this seems strange for the exact reasons that you mentioned

> The linker options appear in the command line in the following order:
> 
> * first, the options provided by environment variables and `sysconfig` variables,
> * then, a `-L` option for each element of `Extension.library_dirs`,
> * then, a linker-specific option like `-Wl,-rpath` for each element of `Extension.runtime_library_dirs`,
> * finally, the options provided by `Extension.extra_link_args`.

The fact that you can set enviornmental variables that get picked up by `python -m build` was the whole point of https://github.com/scikit-hep/pyhf/pull/1887, so this is confusing.

**Comment by matthewfeickert** [comment]
I rebuild the wheels and the only difference that I can see when looking at their logs is where `-latomic` gets placed

```console
$ LDFLAGS="-latomic" python -m build . &> LDFLAGS_build_out.txt
$ grep latomic LDFLAGS_build_out.txt 
arm-linux-gnueabihf-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -latomic build/temp.linux-armv7l-cpython-39/src/module.o build/temp.linux-armv7l-cpython-39/src/register_accumulators.o build/temp.linux-armv7l-cpython-39/src/register_algorithm.o build/temp.linux-armv7l-cpython-39/src/register_axis.o build/temp.linux-armv7l-cpython-39/src/register_histograms.o build/temp.linux-armv7l-cpython-39/src/register_storage.o build/temp.linux-armv7l-cpython-39/src/register_transforms.o -L/usr/lib -o build/lib.linux-armv7l-cpython-39/boost_histogram/_core.cpython-39-arm-linux-gnueabihf.so
```

vs.

```console
$ python -m build . &> patch_build_out.txt
$ grep latomic patch_build_out.txt 
arm-linux-gnueabihf-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 build/temp.linux-armv7l-cpython-39/src/module.o build/temp.linux-armv7l-cpython-39/src/register_accumulators.o build/temp.linux-armv7l-cpython-39/src/register_algorithm.o build/temp.linux-armv7l-cpython-39/src/register_axis.o build/temp.linux-armv7l-cpython-39/src/register_histograms.o build/temp.linux-armv7l-cpython-39/src/register_storage.o build/temp.linux-armv7l-cpython-39/src/register_transforms.o -L/usr/lib -o build/lib.linux-armv7l-cpython-39/boost_histogram/_core.cpython-39-arm-linux-gnueabihf.so -latomic
```

**Comment by matthewfeickert** [comment]
@bennuttall Now that [`boost-histogram` `v1.4.0`](https://github.com/scikit-hep/boost-histogram/releases/tag/v1.4.0) is out could you attempt this build again?

**Comment by bennuttall** [comment]
That built ok for me.

We're currently working through the backlog of Python 3.11 builds so it'll try those in the next few days and then it'll try 1.4.0 on Buster and Bullseye once we re-introduce those builders.

**Comment by matthewfeickert** [comment]
Thanks very much @bennuttall. SGTM!

**Comment by MichaIng** [comment]
Memory ist still/again the issue:
```
2026-02-11T13:24:57,315   virtual memory exhausted: Cannot allocate memory
```

**Comment by henryiii** [comment]
Have you made sure it's a single threaded build? `-Ccmake.define.CMAKE_BUILD_PARALLEL_LEVEL=1` when building or set the env var `CMAKE_BUILD_PARALLEL_LEVEL=1` (This is for any version after we moved to scikit-build-core, assuming you are trying a fairly recent version). It usually only overflows memory in multithreaded builds.

**Comment by matthewfeickert** [comment]
(I'm not suggesting that this issue be closed, but in full disclosure as the person who opened this issue, I've moved onto using conda-forge distributions on my `aarch64` RPi and so am not affected by it anymore. If this is taking up maintainer time I would suggest to close it and suggest that people use other methods of installation.)

**Comment by MichaIng** [comment]
Generally environment variables can be set here: https://github.com/piwheels/piwheels/blob/main/piwheels/slave/builder.py#L470
Currently not sure whether there is a way to set per-package variables, since `CMAKE_BUILD_PARALLEL_LEVEL=1` might slow down other builds which do not crash 🤔. But otherwise a great idea. In other contexts I was sort of annoyed that I couldn't find a way to limit parallel build jobs/threads through `pip` and the build backend, but maybe I was just looking at the wrong place.

> If this is taking up maintainer time I would suggest to close it and suggest that people use other methods of installation.

IMO, good to keep this issue open, and I added a new label indicating an issue that is affecting a number of more packages. Maybe this can be solved for all of them by raising the swap size, or per-package by passing `CMAKE_BUILD_PARALLEL_LEVEL=1` (or `=2`) where `cmake` is used, or it does more good than harm to set this variable for all builds: Swapping slows down things massively, so often if 4 parallel jobs require swapping, while allowing only 1 does not, it is faster to use just one.

**Comment by henryiii** [comment]
Do you know how much memory is available? It looks to me like it is mostly dominated by the linking step at the end, unless you build with more than 4 threads (how many cores it thinks it has would be interesting too).

**Comment by MichaIng** [comment]
I read somewhere 1 GB swap. And I guess 4 GB RAM (since 1 GB would not be sufficient for anything, 8 GB would not have this issue, and mythic beasts offers no other RPi 4 models). It is Raspberry Pi 4 hardware, hence 4 cores.
