### ISSUE TITLE
Missing package: depthai

### ISSUE THREAD

**Issue by jabberjabberjabber** [piwheels/packages#363]
### Package name

depthai

### Package version

2.20.1.0

### PyPI URL

https://pypi.org/project/depthai/

### piwheels URL

https://www.piwheels.org/project/depthai/

### Python version

- [ ] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

Seems to fail when running out of virtual memory.

```
2023-04-06T06:18:27,045   virtual memory exhausted: Cannot allocate memory
2023-04-06T06:18:27,196   gmake[2]: *** [CMakeFiles/depthai.dir/build.make:76: CMakeFiles/depthai.dir/src/py_bindings.cpp.o] Error 1
2023-04-06T06:18:27,197   gmake[1]: *** [CMakeFiles/Makefile2:182: CMakeFiles/depthai.dir/all] Error 2
2023-04-06T06:18:27,197   gmake: *** [Makefile:136: all] Error 2
2023-04-06T06:18:27,215   Traceback (most recent call last):
2023-04-06T06:18:27,215     File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
2023-04-06T06:18:27,216       main()
2023-04-06T06:18:27,217     File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
2023-04-06T06:18:27,217       json_out['return_val'] = hook(**hook_input['kwargs'])
2023-04-06T06:18:27,217     File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
2023-04-06T06:18:27,218       return _build_backend().build_wheel(wheel_directory, config_settings,
2023-04-06T06:18:27,218     File "/tmp/pip-build-env-b8rn_2nc/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 413, in build_wheel
2023-04-06T06:18:27,219       return self._build_with_temp_dir(['bdist_wheel'], '.whl',
2023-04-06T06:18:27,219     File "/tmp/pip-build-env-b8rn_2nc/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 398, in _build_with_temp_dir
2023-04-06T06:18:27,219       self.run_setup()
2023-04-06T06:18:27,219     File "/tmp/pip-build-env-b8rn_2nc/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 484, in run_setup
2023-04-06T06:18:27,220       super(_BuildMetaLegacyBackend,
2023-04-06T06:18:27,220     File "/tmp/pip-build-env-b8rn_2nc/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
2023-04-06T06:18:27,221       exec(code, locals())
2023-04-06T06:18:27,221     File "<string>", line 193, in <module>
2023-04-06T06:18:27,222     File "/tmp/pip-build-env-b8rn_2nc/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 108, in setup
2023-04-06T06:18:27,222       return distutils.core.setup(**attrs)
2023-04-06T06:18:27,223     File "/tmp/pip-build-env-b8rn_2nc/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
2023-04-06T06:18:27,223       return run_commands(dist)
2023-04-06T06:18:27,223     File "/tmp/pip-build-env-b8rn_2nc/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
2023-04-06T06:18:27,224       dist.run_commands()
2023-04-06T06:18:27,224     File "/tmp/pip-build-env-b8rn_2nc/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
2023-04-06T06:18:27,225       self.run_command(cmd)
2023-04-06T06:18:27,225     File "/tmp/pip-build-env-b8rn_2nc/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1221, in run_command
2023-04-06T06:18:27,226       super().run_command(command)
2023-04-06T06:18:27,226     File "/tmp/pip-build-env-b8rn_2nc/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
2023-04-06T06:18:27,227       cmd_obj.run()
2023-04-06T06:18:27,227     File "/tmp/pip-build-env-b8rn_2nc/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 343, in run
2023-04-06T06:18:27,228       self.run_command("build")
2023-04-06T06:18:27,228     File "/tmp/pip-build-env-b8rn_2nc/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
2023-04-06T06:18:27,228       self.distribution.run_command(command)
2023-04-06T06:18:27,228     File "/tmp/pip-build-env-b8rn_2nc/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1221, in run_command
2023-04-06T06:18:27,229       super().run_command(command)
2023-04-06T06:18:27,230     File "/tmp/pip-build-env-b8rn_2nc/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
2023-04-06T06:18:27,230       cmd_obj.run()
2023-04-06T06:18:27,231     File "/tmp/pip-build-env-b8rn_2nc/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
2023-04-06T06:18:27,231       self.run_command(cmd_name)
2023-04-06T06:18:27,231     File "/tmp/pip-build-env-b8rn_2nc/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
2023-04-06T06:18:27,232       self.distribution.run_command(command)
2023-04-06T06:18:27,232     File "/tmp/pip-build-env-b8rn_2nc/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1221, in run_command
2023-04-06T06:18:27,233       super().run_command(command)
2023-04-06T06:18:27,233     File "/tmp/pip-build-env-b8rn_2nc/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
2023-04-06T06:18:27,234       cmd_obj.run()
2023-04-06T06:18:27,234     File "<string>", line 92, in run
2023-04-06T06:18:27,234     File "<string>", line 191, in build_extension
2023-04-06T06:18:27,234     File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
2023-04-06T06:18:27,235       raise CalledProcessError(retcode, cmd)
2023-04-06T06:18:27,235   subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j1']' returned non-zero exit status 2.
2023-04-06T06:18:27,315   ERROR: [present-rich] Building wheel for depthai (pyproject.toml) exited with 1
2023-04-06T06:18:27,333   [bold magenta]full command[/]: [blue]/usr/bin/python3 /usr/local/lib/python3.9/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmph27skb7r[/]
2023-04-06T06:18:27,333   [bold magenta]cwd[/]: /tmp/pip-wheel-gj4aeqj7/depthai_cdf30eb73842442aac2eb7ee06d1644c
2023-04-06T06:18:27,333   Building wheel for depthai (pyproject.toml): finished with status 'error'
2023-04-06T06:18:27,336   ERROR: Failed building wheel for depthai
2023-04-06T06:18:27,338 Failed to build depthai
2023-04-06T06:18:27,339 ERROR: Failed to build one or more wheels
2023-04-06T06:18:27,340 Exception information:
2023-04-06T06:18:27,340 Traceback (most recent call last):
2023-04-06T06:18:27,340   File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
2023-04-06T06:18:27,340     status = run_func(*args)
2023-04-06T06:18:27,340   File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
2023-04-06T06:18:27,340     return func(self, options, args)
2023-04-06T06:18:27,340   File "/usr/local/lib/python3.9/dist-packages/pip/_internal/commands/wheel.py", line 201, in run
2023-04-06T06:18:27,340     raise CommandError("Failed to build one or more wheels")
2023-04-06T06:18:27,340 pip._internal.exceptions.CommandError: Failed to build one or more wheels
2023-04-06T06:18:27,344 Removed build tracker: '/tmp/pip-build-tracker-5m_lo27i'
```

https://www.piwheels.org/logs/0000/0955/8468.txt

Any chance this could get fixed? Thanks.

**Comment by themarpe** [comment]
@jabberjabberjabber we have armv6 builds available here

```python3 -m pip install --extra-index-url https://artifacts.luxonis.com/artifactory/luxonis-python-release-local/ depthai```

@bennuttall as we are running out of memory on most recent bindings builds, would it be possible to let piwheels project instead download the existing armv6l/armv7l precompiled wheels, or for us to upload them explicitly?

There might be some workarounds, but we are likely running out of runway here, given the limited amount of ram available on piwheel builders.

**Comment by MichaIng** [comment]
Recent builds do not seem to fail because of memory, but:
```
2025-08-31T04:56:30,767   CMake Warning:
2025-08-31T04:56:30,768     Ignoring extra path from command line:

2025-08-31T04:56:30,769      "/tmp"


2025-08-31T04:56:30,771   CMake Error: The source directory "/tmp" does not appear to contain CMakeLists.txt.
```
🤔

**Comment by MichaIng** [comment]
Ah, an sdist is not provided, so piwheels cannot build it. Binary wheels are provided for `x86_64` and `aarch64` only: https://pypi.org/project/depthai/#files

Closing this.
