### ISSUE TITLE
Problem with package: scikit-surprise

### ISSUE THREAD

**Issue by priyanshi129** [piwheels/packages#386]
### Package name

scikit-surprise

### Package version

1.17

### PyPI URL

https://pypi.org/project/scikit-surprise/

### piwheels URL

https://www.piwheels.org/project/scikit-surprise/

### Python version

- [X] Python 3.7
- [ ] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

C:\Users\dell>pip3 install scikit-surprise
Collecting scikit-surprise
  Using cached scikit-surprise-1.1.3.tar.gz (771 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [59 lines of output]
      <string>:65: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
      C:\Users\dell\AppData\Local\Programs\Python\Python311\python.exe: No module named pip
      Traceback (most recent call last):
        File "C:\Users\dell\AppData\Local\Temp\pip-build-env-x9hyhs63\overlay\Lib\site-packages\setuptools\installer.py", line 101, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "C:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python311\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\dell\\AppData\\Local\\Temp\\tmpprgzwnt7', '--quiet', 'numpy>=1.17.3']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "C:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\dell\AppData\Local\Temp\pip-build-env-x9hyhs63\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\dell\AppData\Local\Temp\pip-build-env-x9hyhs63\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\dell\AppData\Local\Temp\pip-build-env-x9hyhs63\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\dell\AppData\Local\Temp\pip-build-env-x9hyhs63\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 65, in <module>
        File "C:\Users\dell\AppData\Local\Temp\pip-build-env-x9hyhs63\overlay\Lib\site-packages\setuptools\dist.py", line 908, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\dell\AppData\Local\Temp\pip-build-env-x9hyhs63\overlay\Lib\site-packages\setuptools\installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\dell\AppData\Local\Temp\pip-build-env-x9hyhs63\overlay\Lib\site-packages\pkg_resources\__init__.py", line 829, in resolve
          dist = self._resolve_dist(
                 ^^^^^^^^^^^^^^^^^^^
        File "C:\Users\dell\AppData\Local\Temp\pip-build-env-x9hyhs63\overlay\Lib\site-packages\pkg_resources\__init__.py", line 865, in _resolve_dist
          dist = best[req.key] = env.best_match(
                                 ^^^^^^^^^^^^^^^
        File "C:\Users\dell\AppData\Local\Temp\pip-build-env-x9hyhs63\overlay\Lib\site-packages\pkg_resources\__init__.py", line 1135, in best_match
          return self.obtain(req, installer)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\dell\AppData\Local\Temp\pip-build-env-x9hyhs63\overlay\Lib\site-packages\pkg_resources\__init__.py", line 1147, in obtain
          return installer(requirement)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\dell\AppData\Local\Temp\pip-build-env-x9hyhs63\overlay\Lib\site-packages\setuptools\installer.py", line 103, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python311\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\dell\\AppData\\Local\\Temp\\tmpprgzwnt7', '--quiet', 'numpy>=1.17.3']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by bennuttall** [comment]
You are running on Windows, but you've filed an issue with the Raspberry Pi Python package repository. Please find the appropriate place to ask for help.
