### ISSUE TITLE
Package issue: rq package installs in Debian Buster but doesn't work

### ISSUE THREAD

**Issue by epower** [piwheels/packages#414]
### Package name

rq

### Package version

1.14.0, 1.14.1, 1.15.0, 1.15.1

### PyPI URL

https://pypi.org/project/rq/

### piwheels URL

https://www.piwheels.org/project/rq/

### Python version

- [X] Python 3.7
- [ ] Python 3.9
- [ ] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [ ] Yes

### More information

The package installs ok but when you try to use it for anything it provides the following error:

```
Nov 29 13:31:43 host python[2103]: Traceback (most recent call last):
Nov 29 13:31:43 host python[2103]:   File "/home/pi/.cache/env/bin/rq", line 8, in <module>
Nov 29 13:31:43 host python[2103]:     sys.exit(main())
Nov 29 13:31:43 host python[2103]:   File "/home/pi/.cache/env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
Nov 29 13:31:43 host python[2103]:     return self.main(*args, **kwargs)
Nov 29 13:31:43 host python[2103]:   File "/home/pi/.cache/env/lib/python3.7/site-packages/click/core.py", line 782, in main
Nov 29 13:31:43 host python[2103]:     rv = self.invoke(ctx)
Nov 29 13:31:43 host python[2103]:   File "/home/pi/.cache/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
Nov 29 13:31:43 host python[2103]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
Nov 29 13:31:43 host python[2103]:   File "/home/pi/.cache/env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
Nov 29 13:31:43 host python[2103]:     return ctx.invoke(self.callback, **ctx.params)
Nov 29 13:31:43 host python[2103]:   File "/home/pi/.cache/env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
Nov 29 13:31:43 host python[2103]:     return callback(*args, **kwargs)
Nov 29 13:31:43 host python[2103]:   File "/home/pi/.cache/env/lib/python3.7/site-packages/rq/cli/helpers.py", line 424, in wrapper
Nov 29 13:31:43 host python[2103]:     return ctx.invoke(func, cli_config, *args[1:], **kwargs)
Nov 29 13:31:43 host python[2103]:   File "/home/pi/.cache/env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
Nov 29 13:31:43 host python[2103]:     return callback(*args, **kwargs)
Nov 29 13:31:43 host python[2103]:   File "/home/pi/.cache/env/lib/python3.7/site-packages/rq/cli/cli.py", line 251, in worker
Nov 29 13:31:43 host python[2103]:     cleanup_ghosts(cli_config.connection)
Nov 29 13:31:43 host python[2103]:   File "/home/pi/.cache/env/lib/python3.7/site-packages/rq/contrib/legacy.py", line 20, in cleanup_ghosts
Nov 29 13:31:43 host python[2103]:     for worker in Worker.all(connection=conn):
Nov 29 13:31:43 host python[2103]:   File "/home/pi/.cache/env/lib/python3.7/site-packages/rq/worker.py", line 261, in all
Nov 29 13:31:43 host python[2103]:     for key in worker_keys
Nov 29 13:31:43 host python[2103]:   File "/home/pi/.cache/env/lib/python3.7/site-packages/rq/worker.py", line 261, in <listcomp>
Nov 29 13:31:43 host python[2103]:     for key in worker_keys
Nov 29 13:31:43 host python[2103]:   File "/home/pi/.cache/env/lib/python3.7/site-packages/rq/worker.py", line 685, in find_by_key
Nov 29 13:31:43 host python[2103]:     worker.refresh()
Nov 29 13:31:43 host python[2103]:   File "/home/pi/.cache/env/lib/python3.7/site-packages/rq/worker.py", line 1041, in refresh
Nov 29 13:31:43 host python[2103]:     queues = as_text(queues)
Nov 29 13:31:43 host python[2103]:   File "/home/pi/.cache/env/lib/python3.7/site-packages/rq/utils.py", line 58, in as_text
Nov 29 13:31:43 host python[2103]:     raise ValueError('Unknown type %r' % type(v))
Nov 29 13:31:43 host python[2103]: ValueError: Unknown type <class 'NoneType'>
```

Versions from 1.13.0 and older still work ok. All later version appear to have this issue.

**Comment by MichaIng** [comment]
I'm closing this. Let us know if the recent wheels still fail on respective Debian/Raspbian versions.
