### ISSUE TITLE
Problem with package: xgboost

### ISSUE THREAD

**Issue by mtobin-tdab** [piwheels/packages#436]
### Package name

xgboost

### Package version

2.0.3

### PyPI URL

https://pypi.org/project/xgboost/

### piwheels URL

https://www.piwheels.org/project/xgboost/

### Python version

- [ ] Python 3.7
- [X] Python 3.9
- [ ] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [ ] Yes

### I am the maintainer

- [ ] Yes

### More information

The 2.0.3 wheel for xgboost linux/arm/7 can be installed but not run. It produces the following result:

Python 3.9.18 (main, Mar 12 2024, 06:33:39)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xgboost
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/code/.venv/lib/python3.9/site-packages/xgboost/__init__.py", line 7, in <module>
    from . import collective, dask, rabit
  File "/code/.venv/lib/python3.9/site-packages/xgboost/collective.py", line 12, in <module>
    from .core import _LIB, _check_call, c_str, from_pystr_to_cstr, py_str
  File "/code/.venv/lib/python3.9/site-packages/xgboost/core.py", line 267, in <module>
    _LIB = _load_lib()
  File "/code/.venv/lib/python3.9/site-packages/xgboost/core.py", line 217, in _load_lib
    raise XGBoostError(
xgboost.core.XGBoostError:
XGBoost Library (libxgboost.so) could not be loaded.
Likely causes:
  * OpenMP runtime is not installed
    - vcomp140.dll or libgomp-1.dll for Windows
    - libomp.dylib for Mac OSX
    - libgomp.so for Linux and other UNIX-like OSes
    Mac OSX users: Run `brew install libomp` to install OpenMP runtime.

  * You are running 32-bit Python on a 64-bit OS

Error message(s): ["/usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /code/.venv/lib/python3.9/site-packages/xgboost/lib/libxgboost.so)"]

### Running on:

Linux 97949f311687 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux

Hardware        : BCM2835
Revision        : a020d3
Serial          : 00000000d8e74aaf
Model           : Raspberry Pi 3 Model B Plus Rev 1.3

**Comment by bennuttall** [comment]
Did you install the apt dependencies listed here: https://www.piwheels.org/project/xgboost/

And also for any dependencies of this package?

**Comment by mtobin-tdab** [comment]
Did you manage to recreate this issue?

**Comment by MichaIng** [comment]
Is this still an issue with recent wheels? If so:
```
version `GLIBCXX_3.4.29' not found
```
Might it be the cp39 > cp311 issue here, so Python 3.9 wheels are built on the wrong Debian version, hence requiring too new glibc versions or so?

**Comment by MichaIng** [comment]
Reason is that this wheel gets a `py3-none-manylinux_2_36` tag on all distro/Python versions. So those builds overwrite each other, and only a single wheel is distributed. Since piwheels builds dynamically link libraries, the wheel however usually works on a single distro version only.

EDIT: And Bullseye ships libc6 2.31, while 2.36 requires Bookworm or newer.
