### ISSUE TITLE
Missing package: jaxlib

### ISSUE THREAD

**Issue by qwertpi** [piwheels/packages#44]
Package name: jaxlib
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/jaxlib/
Link to piwheels page: https://piwheels.org/project/jaxlib/
Version: e.g. all
Python version: e.g. all
More information: it seems that source code isn't distributed by PyPI but instead [here]( https://github.com/google/jax) along with build instructions

**Comment by bennuttall** [comment]
Have you tried building it?

**Comment by qwertpi** [comment]
> Have you tried building it?

It downloads x86 bazel during install which of course then errors when it tries to use it, I'm attempting to compile an arm bazel using [this](https://gist.github.com/EKami/9869ae6347f68c592c5b5cd181a3b205#3-build-bazel)

**Comment by qwertpi** [comment]
> > Have you tried building it?
> 
> It downloads x86 bazel during install which of course then errors when it tries to use it, I'm attempting to compile an arm bazel using [this](https://gist.github.com/EKami/9869ae6347f68c592c5b5cd181a3b205#3-build-bazel)

I got it to install usimg [this precompiled bazel](https://github.com/dilbrent/bazel/releases) but when I try to import jax I get the error 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/jax/jax/__init__.py", line 19, in <module>
    from jax.api import *
  File "/home/pi/jax/jax/api.py", line 44, in <module>
    from . import ad_util
  File "/home/pi/jax/jax/ad_util.py", line 20, in <module>
    from .tree_util import register_pytree_node
  File "/home/pi/jax/jax/tree_util.py", line 43, in <module>
    from .lib import pytree
  File "/home/pi/jax/jax/lib/__init__.py", line 40, in <module>
    from jaxlib import xla_client
ImportError: cannot import name 'xla_client
```

**Comment by qwertpi** [comment]
> > > Have you tried building it?
> > 
> > 
> > It downloads x86 bazel during install which of course then errors when it tries to use it, I'm attempting to compile an arm bazel using [this](https://gist.github.com/EKami/9869ae6347f68c592c5b5cd181a3b205#3-build-bazel)
> 
> I got it to install usimg [this precompiled bazel](https://github.com/dilbrent/bazel/releases) but when I try to import jax I get the error
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/pi/jax/jax/__init__.py", line 19, in <module>
>     from jax.api import *
>   File "/home/pi/jax/jax/api.py", line 44, in <module>
>     from . import ad_util
>   File "/home/pi/jax/jax/ad_util.py", line 20, in <module>
>     from .tree_util import register_pytree_node
>   File "/home/pi/jax/jax/tree_util.py", line 43, in <module>
>     from .lib import pytree
>   File "/home/pi/jax/jax/lib/__init__.py", line 40, in <module>
>     from jaxlib import xla_client
> ImportError: cannot import name 'xla_client
> ```

I did get a warning about an out of date version of Bazel while building. Does anyone have an up to date raspberry pi compatible Bazel executable they could send me?

**Comment by bennuttall** [comment]
I think we need to get the maintainers to support Raspberry Pi for this to happen. I've opened an issue upstream: https://github.com/google/jax/issues/1161

**Comment by bennuttall** [comment]
Closing due to no activity.

**Comment by esillekens** [comment]
I have tried building it today, it crashed after a few hour. I got a lot further though.

[build_error.txt](https://github.com/piwheels/packages/files/9923326/build_error.txt)

**Comment by bennuttall** [comment]
They've closed the issue https://github.com/google/jax/issues/1161

They say aarch64 wheels are available now
