### ISSUE TITLE
Missing package: pygame-ce (only v2.5.0)

### ISSUE THREAD

**Issue by ankith26** [piwheels/packages#454]
### Package name

pygame-ce

### Package version

2.5.0

### PyPI URL

https://pypi.org/project/pygame-ce/

### piwheels URL

https://www.piwheels.org/project/pygame-ce/

### Python version

- [ ] Python 3.7
- [ ] Python 3.9
- [X] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [X] Yes

### More information

The publicly available build logs show the following in the last few lines:
```
2024-06-12T05:01:00,234 Collecting pygame-ce==2.5.0
2024-06-12T05:01:00,236   Created temporary directory: /tmp/pip-unpack-kk56wqsu
2024-06-12T05:01:00,463   Downloading pygame_ce-2.5.0.tar.gz (6.1 MB)
2024-06-12T05:01:01,428 ERROR: Exception:
2024-06-12T05:01:01,428 Traceback (most recent call last):
2024-06-12T05:01:01,428   File "/usr/local/lib/python3.11/dist-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
2024-06-12T05:01:01,428     status = run_func(*args)
2024-06-12T05:01:01,428              ^^^^^^^^^^^^^^^
2024-06-12T05:01:01,428   File "/usr/local/lib/python3.11/dist-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
2024-06-12T05:01:01,428     return func(self, options, args)
2024-06-12T05:01:01,428            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-12T05:01:01,428   File "/usr/local/lib/python3.11/dist-packages/pip/_internal/commands/wheel.py", line 147, in run
2024-06-12T05:01:01,428     requirement_set = resolver.resolve(reqs, check_supported_wheels=True)
2024-06-12T05:01:01,428                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-12T05:01:01,428   File "/usr/local/lib/python3.11/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
2024-06-12T05:01:01,428     result = self._result = resolver.resolve(
2024-06-12T05:01:01,428                             ^^^^^^^^^^^^^^^^^
2024-06-12T05:01:01,428   File "/usr/local/lib/python3.11/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
2024-06-12T05:01:01,428     state = resolution.resolve(requirements, max_rounds=max_rounds)
2024-06-12T05:01:01,428             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-12T05:01:01,428   File "/usr/local/lib/python3.11/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
2024-06-12T05:01:01,428     self._add_to_criteria(self.state.criteria, r, parent=None)
2024-06-12T05:01:01,428   File "/usr/local/lib/python3.11/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
2024-06-12T05:01:01,428     if not criterion.candidates:
2024-06-12T05:01:01,428   File "/usr/local/lib/python3.11/dist-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
2024-06-12T05:01:01,428     return bool(self._sequence)
2024-06-12T05:01:01,428            ^^^^^^^^^^^^^^^^^^^^
2024-06-12T05:01:01,428   File "/usr/local/lib/python3.11/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
2024-06-12T05:01:01,428     return any(self)
2024-06-12T05:01:01,428            ^^^^^^^^^
2024-06-12T05:01:01,428   File "/usr/local/lib/python3.11/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
2024-06-12T05:01:01,428     return (c for c in iterator if id(c) not in self._incompatible_ids)
2024-06-12T05:01:01,428            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^2024-06-12T05:01:01,445 Removed build tracker: '/tmp/pip-build-tracker-cgcg0l9n'
```
This error only happens on the 3.11 build and not 3.9 build, and I'm almost sure this error is not a fault on our (pygame-ce) end. The pygame-ce 2.5.0.dev4 release which is nearly identical to the pygame-ce 2.5.0 release has been built and distributed by piwheels.

Perhaps this issue could be fixed by doing a build re-run on your end.

Thanks!

**Comment by bennuttall** [comment]
I've kicked off another build

**Comment by bennuttall** [comment]
It's built now

**Comment by ankith26** [comment]
Thanks for the quick issue resolution :)
