### ISSUE TITLE
[pyrf24] Package issue: fatal error: ... No space left on device

### ISSUE THREAD

**Issue by 2bndy5** [piwheels/packages#455]
### Package name

pyrf24

### Package version

0.4.0

### PyPI URL

https://pypi.org/project/pyrf24

### piwheels URL

https://www.piwheels.org/project/pyrf24/

### Python version

- [ ] Python 3.7
- [ ] Python 3.9
- [X] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [X] Yes

### More information

I test built this release on my RPi3 (RPi OS lite 32-bit with Python v3.11.2) using the [pypa/build package](https://pypi.org/project/build/), and there was no problems.

The sdist that I uploaded to PyPI was also created similarly (in CI) using `python -m build -s`.

In the build logs I see the following the error:
```
fatal error: error closing /tmp/ccvPvu4d.s: No space left on device
```
Is this specific to the piwheels' slave device? The C++ codebase that we're compiling is not that big (full package source at [nRF24/pyRF24](https://github.com/nRF24/pyRF24)).

<details><summary>full build log</summary>

```
2024-06-16T03:51:04,543 Building wheels for collected packages: pyrf24
2024-06-16T03:51:04,548   Created temporary directory: /tmp/pip-wheel-irssy7lj
2024-06-16T03:51:04,549   Destination directory: /tmp/pip-wheel-irssy7lj
2024-06-16T03:51:04,551   Building wheel for pyrf24 (pyproject.toml): started
2024-06-16T03:51:04,553   Running command Building wheel for pyrf24 (pyproject.toml)
2024-06-16T03:51:05,425   running bdist_wheel
2024-06-16T03:51:05,443   running build
2024-06-16T03:51:05,444   running build_py
2024-06-16T03:51:05,449   creating build
2024-06-16T03:51:05,450   creating build/lib.linux-armv7l-cpython-311
2024-06-16T03:51:05,450   creating build/lib.linux-armv7l-cpython-311/pyrf24
2024-06-16T03:51:05,452   copying src/pyrf24/__init__.py -> build/lib.linux-armv7l-cpython-311/pyrf24
2024-06-16T03:51:05,454   copying src/pyrf24/fake_ble.py -> build/lib.linux-armv7l-cpython-311/pyrf24
2024-06-16T03:51:05,456   running egg_info
2024-06-16T03:51:05,463   writing pyrf24.egg-info/PKG-INFO
2024-06-16T03:51:05,467   writing dependency_links to pyrf24.egg-info/dependency_links.txt
2024-06-16T03:51:05,468   writing top-level names to pyrf24.egg-info/top_level.txt
2024-06-16T03:51:05,494   ERROR setuptools_scm._file_finders.git listing git files failed - pretending there aren't any
2024-06-16T03:51:05,497   reading manifest file 'pyrf24.egg-info/SOURCES.txt'
2024-06-16T03:51:05,502   reading manifest template 'MANIFEST.in'
2024-06-16T03:51:05,573   warning: no previously-included files matching '*' found under directory '*/.github'
2024-06-16T03:51:05,574   warning: no previously-included files matching '*' found under directory '*/docs'
2024-06-16T03:51:05,575   warning: no previously-included files matching '*' found under directory '*/examples*'
2024-06-16T03:51:05,576   warning: no previously-included files matching '*' found under directory '.github'
2024-06-16T03:51:05,577   warning: no previously-included files matching '*' found under directory 'docs'
2024-06-16T03:51:05,577   warning: no previously-included files matching '*' found under directory 'examples*'
2024-06-16T03:51:05,579   warning: no previously-included files matching '*' found under directory '*/images'
2024-06-16T03:51:05,580   warning: no previously-included files matching '*' found under directory '*/tests'
2024-06-16T03:51:05,581   warning: no previously-included files matching '*' found under directory '*/build'
2024-06-16T03:51:05,582   warning: no previously-included files matching '*.cmake' found under directory '*/cmake/toolchains'
2024-06-16T03:51:05,582   warning: no previously-included files matching '*.h' found under directory 'RF24/utility/AT*'
2024-06-16T03:51:05,583   warning: no previously-included files matching '*.cpp' found under directory 'RF24/utility/AT*'
2024-06-16T03:51:05,584   warning: no previously-included files matching '*.c' found under directory 'RF24/utility/AT*'
2024-06-16T03:51:05,585   warning: no previously-included files matching '*.h' found under directory 'RF24/utility/Teensy'
2024-06-16T03:51:05,586   warning: no previously-included files matching '*.h' found under directory 'RF24/utility/Template*'
2024-06-16T03:51:05,587   warning: no previously-included files matching '*.h' found under directory 'RF24/utility/rp2'
2024-06-16T03:51:05,587   warning: no previously-included files matching '*.cpp' found under directory 'RF24/utility/rp2'
2024-06-16T03:51:05,589   warning: no previously-included files matching '*.txt' found under directory 'RF24/utility/rp2'
2024-06-16T03:51:05,589   warning: no previously-included files matching '*' found under directory 'RF24*/pyRF24*'
2024-06-16T03:51:05,590   warning: no previously-included files matching '*' found under directory 'RF24Network/RPi/pyRF24Network'
2024-06-16T03:51:05,591   warning: no previously-included files matching '.clang-format' found anywhere in distribution
2024-06-16T03:51:05,592   warning: no previously-included files matching '.clang-tidy' found anywhere in distribution
2024-06-16T03:51:05,593   warning: no previously-included files matching '.git*' found anywhere in distribution
2024-06-16T03:51:05,594   warning: no previously-included files matching 'library.json' found anywhere in distribution
2024-06-16T03:51:05,595   warning: no previously-included files matching 'library.properties' found anywhere in distribution
2024-06-16T03:51:05,596   warning: no previously-included files matching 'Doxyfile' found anywhere in distribution
2024-06-16T03:51:05,597   warning: no previously-included files matching 'keywords.txt' found anywhere in distribution
2024-06-16T03:51:05,598   warning: no previously-included files matching 'Makefile*' found anywhere in distribution
2024-06-16T03:51:05,599   warning: no previously-included files matching 'doxygen-custom.css' found anywhere in distribution
2024-06-16T03:51:05,601   warning: no previously-included files matching '**.yml' found anywhere in distribution
2024-06-16T03:51:05,603   warning: no previously-included files matching '**.yaml' found anywhere in distribution
2024-06-16T03:51:05,604   warning: no previously-included files matching '*.pdf' found anywhere in distribution
2024-06-16T03:51:05,605   warning: no previously-included files found matching '*/*.md'
2024-06-16T03:51:05,606   warning: no previously-included files found matching '*/README*'
2024-06-16T03:51:05,607   warning: no previously-included files found matching 'RF24/utility/includes.h'
2024-06-16T03:51:05,607   warning: no previously-included files found matching 'RF24/configure'
2024-06-16T03:51:05,608   adding license file 'LICENSE'
2024-06-16T03:51:05,616   writing manifest file 'pyrf24.egg-info/SOURCES.txt'
2024-06-16T03:51:05,623   copying src/pyrf24/py.typed -> build/lib.linux-armv7l-cpython-311/pyrf24
2024-06-16T03:51:05,625   copying src/pyrf24/pyrf24.pyi -> build/lib.linux-armv7l-cpython-311/pyrf24
2024-06-16T03:51:05,629   running build_ext
2024-06-16T03:51:05,987   -- The C compiler identification is GNU 12.2.0
2024-06-16T03:51:06,369   -- The CXX compiler identification is GNU 12.2.0
2024-06-16T03:51:06,423   -- Detecting C compiler ABI info
2024-06-16T03:51:06,802   -- Detecting C compiler ABI info - done
2024-06-16T03:51:06,843   -- Check for working C compiler: /usr/bin/cc - skipped
2024-06-16T03:51:06,844   -- Detecting C compile features
2024-06-16T03:51:06,846   -- Detecting C compile features - done
2024-06-16T03:51:06,865   -- Detecting CXX compiler ABI info
2024-06-16T03:51:07,330   -- Detecting CXX compiler ABI info - done
2024-06-16T03:51:07,373   -- Check for working CXX compiler: /usr/bin/c++ - skipped
2024-06-16T03:51:07,375   -- Detecting CXX compile features
2024-06-16T03:51:07,377   -- Detecting CXX compile features - done
2024-06-16T03:51:07,405   -- pybind11 v2.10.4
2024-06-16T03:51:07,490   -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.11.2", minimum required is "3.6")
2024-06-16T03:51:07,578   -- Found PythonLibs: /usr/lib/arm-linux-gnueabihf/libpython3.11.so
2024-06-16T03:51:07,590   -- Performing Test HAS_FLTO
2024-06-16T03:51:08,297   -- Performing Test HAS_FLTO - Success
2024-06-16T03:51:08,322   -- Using driver: SPIDEV
2024-06-16T03:51:08,329   CMake Warning at RF24/utility/CMakeLists.txt:42 (message):
2024-06-16T03:51:08,330     Detecting /dev/spidev0.0 failed - continuing anyway.  Please make sure SPI
2024-06-16T03:51:08,331     is enabled.


2024-06-16T03:51:08,345   -- Supplementing SPIDEV driver with linux/gpio.h
2024-06-16T03:51:08,348   -- Configuring done
2024-06-16T03:51:08,414   -- Generating done
2024-06-16T03:51:08,431   -- Build files have been written to: /tmp/pip-wheel-u849n6l_/pyrf24_b20fbf72b9fc4b3ba032b92c62b1e55c/build/temp.linux-armv7l-cpython-311/pyrf24
2024-06-16T03:51:08,694   [  8%] Building CXX object CMakeFiles/pyrf24.dir/RF24/RF24.cpp.o
2024-06-16T03:51:10,089   [ 16%] Building CXX object CMakeFiles/pyrf24.dir/RF24/utility/SPIDEV/gpio.cpp.o
2024-06-16T03:51:11,665   [ 25%] Building CXX object CMakeFiles/pyrf24.dir/RF24/utility/SPIDEV/spi.cpp.o
2024-06-16T03:51:12,717   [ 33%] Building CXX object CMakeFiles/pyrf24.dir/RF24/utility/SPIDEV/compatibility.cpp.o
2024-06-16T03:51:13,150   [ 41%] Building CXX object CMakeFiles/pyrf24.dir/RF24/utility/SPIDEV/interrupt.cpp.o
2024-06-16T03:51:14,763   [ 50%] Building CXX object CMakeFiles/pyrf24.dir/RF24Network/RF24Network.cpp.o
2024-06-16T03:51:17,151   [ 58%] Building CXX object CMakeFiles/pyrf24.dir/RF24Mesh/RF24Mesh.cpp.o
2024-06-16T03:51:19,164   [ 66%] Building CXX object CMakeFiles/pyrf24.dir/src/pyRF24.cpp.o
2024-06-16T03:51:40,271   /tmp/pip-wheel-u849n6l_/pyrf24_b20fbf72b9fc4b3ba032b92c62b1e55c/src/pyRF24.cpp:1212:1: fatal error: error closing /tmp/ccvPvu4d.s: No space left on device
2024-06-16T03:51:40,272    1212 | }
2024-06-16T03:51:40,273         | ^
2024-06-16T03:51:40,273   compilation terminated.
2024-06-16T03:51:40,308   gmake[2]: *** [CMakeFiles/pyrf24.dir/build.make:174: CMakeFiles/pyrf24.dir/src/pyRF24.cpp.o] Error 1
2024-06-16T03:51:40,311   gmake[1]: *** [CMakeFiles/Makefile2:118: CMakeFiles/pyrf24.dir/all] Error 2
2024-06-16T03:51:40,312   gmake: *** [Makefile:136: all] Error 2
2024-06-16T03:51:40,317   Traceback (most recent call last):
2024-06-16T03:51:40,318     File "/home/piwheels/.local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
2024-06-16T03:51:40,319       main()
2024-06-16T03:51:40,320     File "/home/piwheels/.local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
2024-06-16T03:51:40,321       json_out['return_val'] = hook(**hook_input['kwargs'])
2024-06-16T03:51:40,321                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-16T03:51:40,322     File "/home/piwheels/.local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
2024-06-16T03:51:40,322       return _build_backend().build_wheel(wheel_directory, config_settings,
2024-06-16T03:51:40,322              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-16T03:51:40,323     File "/tmp/pip-build-env-ovcw0c6x/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 410, in build_wheel
2024-06-16T03:51:40,324       return self._build_with_temp_dir(
2024-06-16T03:51:40,325              ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-16T03:51:40,326     File "/tmp/pip-build-env-ovcw0c6x/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
2024-06-16T03:51:40,326       self.run_setup()
2024-06-16T03:51:40,326     File "/tmp/pip-build-env-ovcw0c6x/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 311, in run_setup
2024-06-16T03:51:40,327       exec(code, locals())
2024-06-16T03:51:40,327     File "<string>", line 105, in <module>
2024-06-16T03:51:40,328     File "/tmp/pip-build-env-ovcw0c6x/overlay/local/lib/python3.11/dist-packages/setuptools/__init__.py", line 103, in setup
2024-06-16T03:51:40,328       return distutils.core.setup(**attrs)
2024-06-16T03:51:40,329              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-16T03:51:40,329     File "/tmp/pip-build-env-ovcw0c6x/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/core.py", line 184, in setup
2024-06-16T03:51:40,330       return run_commands(dist)
2024-06-16T03:51:40,330              ^^^^^^^^^^^^^^^^^^
2024-06-16T03:51:40,331     File "/tmp/pip-build-env-ovcw0c6x/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/core.py", line 200, in run_commands
2024-06-16T03:51:40,332       dist.run_commands()
2024-06-16T03:51:40,332     File "/tmp/pip-build-env-ovcw0c6x/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
2024-06-16T03:51:40,333       self.run_command(cmd)
2024-06-16T03:51:40,333     File "/tmp/pip-build-env-ovcw0c6x/overlay/local/lib/python3.11/dist-packages/setuptools/dist.py", line 968, in run_command
2024-06-16T03:51:40,334       super().run_command(command)
2024-06-16T03:51:40,334     File "/tmp/pip-build-env-ovcw0c6x/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
2024-06-16T03:51:40,335       cmd_obj.run()
2024-06-16T03:51:40,336     File "/tmp/pip-build-env-ovcw0c6x/overlay/local/lib/python3.11/dist-packages/wheel/bdist_wheel.py", line 368, in run
2024-06-16T03:51:40,336       self.run_command("build")
2024-06-16T03:51:40,338     File "/tmp/pip-build-env-ovcw0c6x/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/cmd.py", line 316, in run_command
2024-06-16T03:51:40,338       self.distribution.run_command(command)
2024-06-16T03:51:40,340     File "/tmp/pip-build-env-ovcw0c6x/overlay/local/lib/python3.11/dist-packages/setuptools/dist.py", line 968, in run_command
2024-06-16T03:51:40,341       super().run_command(command)
2024-06-16T03:51:40,341     File "/tmp/pip-build-env-ovcw0c6x/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
2024-06-16T03:51:40,343       cmd_obj.run()
2024-06-16T03:51:40,344     File "/tmp/pip-build-env-ovcw0c6x/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/command/build.py", line 132, in run
2024-06-16T03:51:40,344       self.run_command(cmd_name)
2024-06-16T03:51:40,345     File "/tmp/pip-build-env-ovcw0c6x/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/cmd.py", line 316, in run_command
2024-06-16T03:51:40,346       self.distribution.run_command(command)
2024-06-16T03:51:40,347     File "/tmp/pip-build-env-ovcw0c6x/overlay/local/lib/python3.11/dist-packages/setuptools/dist.py", line 968, in run_command
2024-06-16T03:51:40,348       super().run_command(command)
2024-06-16T03:51:40,348     File "/tmp/pip-build-env-ovcw0c6x/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
2024-06-16T03:51:40,349       cmd_obj.run()
2024-06-16T03:51:40,350     File "/tmp/pip-build-env-ovcw0c6x/overlay/local/lib/python3.11/dist-packages/setuptools/command/build_ext.py", line 91, in run
2024-06-16T03:51:40,352       _build_ext.run(self)
2024-06-16T03:51:40,353     File "/tmp/pip-build-env-ovcw0c6x/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
2024-06-16T03:51:40,354       self.build_extensions()
2024-06-16T03:51:40,355     File "/tmp/pip-build-env-ovcw0c6x/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
2024-06-16T03:51:40,355       self._build_extensions_serial()
2024-06-16T03:51:40,356     File "/tmp/pip-build-env-ovcw0c6x/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
2024-06-16T03:51:40,357       self.build_extension(ext)
2024-06-16T03:51:40,357     File "<string>", line 76, in build_extension
2024-06-16T03:51:40,358     File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
2024-06-16T03:51:40,359       raise CalledProcessError(retcode, cmd)
2024-06-16T03:51:40,359   subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 2.
2024-06-16T03:51:40,479   ERROR: Building wheel for pyrf24 (pyproject.toml) exited with 1
2024-06-16T03:51:40,492   [bold magenta]full command[/]: [blue]/usr/bin/python3 /home/piwheels/.local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmpe9qh7xi4[/]
2024-06-16T03:51:40,492   [bold magenta]cwd[/]: /tmp/pip-wheel-u849n6l_/pyrf24_b20fbf72b9fc4b3ba032b92c62b1e55c
2024-06-16T03:51:40,493   Building wheel for pyrf24 (pyproject.toml): finished with status 'error'
2024-06-16T03:51:40,496   ERROR: Failed building wheel for pyrf24
2024-06-16T03:51:40,498 Failed to build pyrf24
```

</details>

**Comment by 2bndy5** [comment]
It looks like a second build attempt has succeeded. Closing. Sorry for the noise. And thank you for this invaluable project!

**Comment by bennuttall** [comment]
I kicked off another build following your report, so thanks.
