### ISSUE TITLE
numpy  libf77blas.so.3 missing

### ISSUE THREAD

**Issue by reimannsum** [piwheels/packages#47]
Package name: numpy
Issue type: Broken package
Link to piwheels page: https://www.piwheels.org/simple/numpy/numpy-1.17.0-cp37-cp37m-linux_armv7l.whl
Version: 1.17.0
Python version: 3.7
More information:

While trying to run
```python
from skyfield.api import Topos
```
I got this error

```python
Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory
```
```bash
Traceback (most recent call last):
File "/usr/local/lib/python3.7/dist-packages/numpy/core/init.py", line 17, in
from . import multiarray
File "/usr/local/lib/python3.7/dist-packages/numpy/core/multiarray.py", line 14, in
from . import overrides
File "/usr/local/lib/python3.7/dist-packages/numpy/core/overrides.py", line 7, in
from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "", line 1, in
File "/usr/local/lib/python3.7/dist-packages/skyfield/api.py", line 13, in
from .iokit import Loader, load_file
File "/usr/local/lib/python3.7/dist-packages/skyfield/iokit.py", line 6, in
import numpy as np
File "/usr/local/lib/python3.7/dist-packages/numpy/init.py", line 142, in
from . import core
File "/usr/local/lib/python3.7/dist-packages/numpy/core/init.py", line 47, in
raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.

    Try uninstalling and reinstalling numpy.

    If you have already done that, then:
        Check that you expected to use Python3.7 from "/usr/bin/python3",
        and that you have no directories in your PATH or PYTHONPATH that can
        interfere with the Python and numpy version "1.17.0" you're trying to use.
        If (1) looks fine, you can open a new issue at
        https://github.com/numpy/numpy/issues. Please include details on:
            how you installed Python
            how you installed numpy
            your operating system
            whether or not you have multiple versions of Python installed
            if you built from source, your compiler versions and ideally a build log

    If you're working with a numpy git repository, try git clean -xdf
    (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory
```

while gathering the info the numpy folks I found that 
```python
import numpy
```
would trigger the same error so I opened a ticket with the folks at numpy, they suggested I may need to come here.

**Comment by bennuttall** [comment]
Did you use the installation instructions here: https://www.piwheels.org/project/numpy ?

![Screenshot from 2019-08-27 12-20-28](https://user-images.githubusercontent.com/1609725/63767314-3b44fc00-c8c5-11e9-83b6-17ad06f8d273.png)

```bash
sudo apt install libatlas3-base libgfortran5
sudo pip3 install numpy
```

**Comment by bennuttall** [comment]
Did this fix it for you?

**Comment by pmirallesr** [comment]
Hello! I encountered the same problem, but when trying to install libgfortran5 I'm told it cannot be located. This is all inside a Docker container

```
Step 13/32 : RUN apt-get update   && apt-get install -y --no-install-recommends     $(awk -F: '/^[^#]/ { print $1 }' dependencies-apt.txt | uniq)   && rm -rf /var/lib/apt/lists/*
 ---> Running in 60e73aa1c317
Get:1 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu xenial InRelease [18.0 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports xenial InRelease [247 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports xenial-updates InRelease [109 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports xenial-backports InRelease [107 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports xenial-security InRelease [109 kB]
Get:6 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu xenial/main Sources [6424 B]
Get:7 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu xenial/main armhf Packages [35.8 kB]
Get:8 http://ports.ubuntu.com/ubuntu-ports xenial/main armhf Packages [1486 kB]
Get:9 http://ports.ubuntu.com/ubuntu-ports xenial/restricted armhf Packages [8491 B]
Get:10 http://ports.ubuntu.com/ubuntu-ports xenial/universe armhf Packages [9531 kB]
Get:11 http://ports.ubuntu.com/ubuntu-ports xenial/multiverse armhf Packages [149 kB]
Get:12 http://ports.ubuntu.com/ubuntu-ports xenial-updates/main armhf Packages [1075 kB]
Get:13 http://ports.ubuntu.com/ubuntu-ports xenial-updates/restricted armhf Packages [8488 B]
Get:14 http://ports.ubuntu.com/ubuntu-ports xenial-updates/universe armhf Packages [925 kB]
Get:15 http://ports.ubuntu.com/ubuntu-ports xenial-updates/multiverse armhf Packages [14.0 kB]
Get:16 http://ports.ubuntu.com/ubuntu-ports xenial-backports/main armhf Packages [7936 B]
Get:17 http://ports.ubuntu.com/ubuntu-ports xenial-backports/universe armhf Packages [8424 B]
Get:18 http://ports.ubuntu.com/ubuntu-ports xenial-security/main armhf Packages [748 kB]
Get:19 http://ports.ubuntu.com/ubuntu-ports xenial-security/restricted armhf Packages [8480 B]
Get:20 http://ports.ubuntu.com/ubuntu-ports xenial-security/universe armhf Packages [552 kB]
Get:21 http://ports.ubuntu.com/ubuntu-ports xenial-security/multiverse armhf Packages [3561 B]
Fetched 15.2 MB in 7s (2016 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libgfortran5
The command '/bin/sh -c apt-get update   && apt-get install -y --no-install-recommends     $(awk -F: '/^[^#]/ { print $1 }' dependencies-apt.txt | uniq)   && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

```

dependencies.txt contains the following:

- libatlas3-base
- libgfortran5

**Comment by pmirallesr** [comment]
I found out that libgfortran5 is not available at https://packages.ubuntu.com/xenial/allpackages and tried to import numpy by installing libgfortran-5-dev and libgfortran3. Both of them produce the following error on importing numpy, I'm guessing they're not appropriate versions:

`ImportError: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.27' not found (required by /usr/local/lib/python3.7/dist-packages/numpy/core/_multiarray_umath.cpython-37m-arm-linux-gnueabihf.so)`

**Comment by bennuttall** [comment]
We don't support Ubuntu. We build on Raspbian for Raspbian. You'll generally need to use Debian or Raspbian for compiled piwheels packages to work.

**Comment by bennuttall** [comment]
This may (or may not) be of some use to you though: https://blog.piwheels.org/how-to-work-out-the-missing-dependencies-for-a-python-package/

**Comment by pmirallesr** [comment]
I see! My bad. The raspberry runs something like raspbian (I believe. It's hypriotOS) but the docker image does not and I did not notice. If I were to use an image based on raspbian (I assume one exists), it should work properly, is that correct?

Thank you for the link, I'll check the method described and try it out. Although from what you say, running an Ubuntu image with piwheels will likely just lead to more issues in the future
