### ISSUE TITLE
Missing package: pyarrow

### ISSUE THREAD

**Issue by MarcelBeining** [piwheels/packages#471]
### Package name

pyarrow

### Package version

all

### PyPI URL

https://pypi.org/project/pyarrow/

### piwheels URL

https://www.piwheels.org/project/pyarrow/

### Python version

- [X] Python 3.9
- [X] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [ ] Yes

### More information

a lot of build seem to have failed here with something like this:

> 
> 2024-07-17T10:51:55,516 Fetching project page and analyzing links: https://www.piwheels.org/simple/pyarrow/
> 2024-07-17T10:51:55,517 Getting page https://www.piwheels.org/simple/pyarrow/
> 2024-07-17T10:51:55,518 Found index url https://www.piwheels.org/simple/
> 2024-07-17T10:51:55,709 Fetched page https://www.piwheels.org/simple/pyarrow/ as text/html
> 2024-07-17T10:51:55,711 Skipping link: not a file: https://www.piwheels.org/simple/pyarrow/
> 2024-07-17T10:51:55,711 Skipping link: not a file: https://pypi.org/simple/pyarrow/
> 2024-07-17T10:51:55,735 Given no hashes to check 1 links for project 'pyarrow': discarding no candidates
> 2024-07-17T10:51:55,754 Collecting pyarrow==17.0.0
> 2024-07-17T10:51:55,757   Created temporary directory: /tmp/pip-unpack-ohjji66y
> 2024-07-17T10:51:55,981   Downloading pyarrow-17.0.0.tar.gz (1.1 MB)
> 2024-07-17T10:51:56,169 ERROR: Exception:
> 2024-07-17T10:51:56,169 Traceback (most recent call last):
> 2024-07-17T10:51:56,169   File "/home/piwheels/.local/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
> 2024-07-17T10:51:56,169     status = run_func(*args)
> 2024-07-17T10:51:56,169              ^^^^^^^^^^^^^^^
> 2024-07-17T10:51:56,169   File "/home/piwheels/.local/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
> 2024-07-17T10:51:56,169     return func(self, options, args)
> 2024-07-17T10:51:56,169            ^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-07-17T10:51:56,169   File "/home/piwheels/.local/lib/python3.11/site-packages/pip/_internal/commands2024-07-17T10:51:56,184 Removed build tracker: '/tmp/pip-build-tracker-kcfyx4vi'

**Comment by MarcelBeining** [comment]
just saw its a duplicate
