### ISSUE TITLE
Missing package: pyinstaller 6.11.0 cp311

### ISSUE THREAD

**Issue by GoetzGoerisch** [piwheels/packages#484]
### Package name

pyinstaller

### Package version

6.11.0

### PyPI URL

https://pypi.org/project/pyinstaller/

### piwheels URL

https://www.piwheels.org/project/pyinstaller/

### Python version

- [ ] Python 3.9
- [X] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [ ] Yes

### More information

From the build log:
```
2024-10-15T22:20:57,392 Given no hashes to check 1 links for project 'pyinstaller': discarding no candidates
2024-10-15T22:20:57,394 Collecting pyinstaller==6.11.0
2024-10-15T22:20:57,397   Created temporary directory: /tmp/pip-unpack-wpad11ud
2024-10-15T22:20:57,614   Downloading pyinstaller-6.11.0.tar.gz (4.2 MB)
2024-10-15T22:20:58,047 ERROR: Exception:
2024-10-15T22:20:58,047 Traceback (most recent call last):
2024-10-15T22:20:58,047   File "/usr/local/lib/python3.11/dist-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
2024-10-15T22:20:58,047     status = _inner_run()
2024-10-15T22:20:58,047              ^^^^^^^^^^^^
2024-10-15T22:20:58,047   File "/usr/local/lib/python3.11/dist-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
2024-10-15T22:20:58,047     return self.run(options, args)
2024-10-15T22:20:58,047            ^^^^^^^^^^^^^^^^^^^^^^^
2024-10-15T22:20:58,047   File "/usr/local/lib/python3.11/dist-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
2024-10-15T22:20:58,047     return func(self, options, args)
2024-10-15T22:20:58,047            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-15T22:20:58,047   File "/usr/local/lib/python3.11/dist-packages/pip/_internal/commands/wheel.py", line 147, in run
2024-10-15T22:20:58,047     requirement_set = resolver.resolve(reqs, check_supported_wheels=True)
2024-10-15T22:20:58,047                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-15T22:20:58,047   File "/usr/local/lib/python3.11/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
2024-10-15T22:20:58,047     result = self._result = resolver.resolve(
2024-10-15T22:20:58,047                             ^^^^^^^^^^^^^^^^^
2024-10-15T22:20:58,047   File "/usr/local/lib/python3.11/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
2024-10-15T22:20:58,047     state = resolution.resolve(requirements, max_rounds=max_rounds)
20242024-10-15T22:20:58,065 Removed build tracker: '/tmp/pip-build-tracker-foy3ll1v'
```

@bennuttall  please requeue for rebuild?

**Comment by bennuttall** [comment]
It failed with the same issue. Not sure what the cause is...

**Comment by MichaIng** [comment]
All wheels > 6.11.0 are present. 6.11.0 Python 3.11 and 3.13 builds and a bunch below are shown as pending. Not sure whether they really have been scheduled recently or this is some sort of visual artifact? Anyway, closing this, as it is unlikely that someone still requires 6.11.0 in particular.
