### ISSUE TITLE
Problem with package: cryptography

### ISSUE THREAD

**Issue by csm10495** [piwheels/packages#491]
### Package name

cryptography

### Package version

43.0.3

### PyPI URL

https://pypi.org/project/cryptography/

### piwheels URL

https://www.piwheels.org/project/cryptography/

### Python version

- [ ] Python 3.9
- [X] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [ ] Yes

### More information

I can't seem to get the latest cryptography (43.0.3) to work on my raspberry pi via docker on bullseye/3.11:

```
C:\Users\csm10495>docker --context pi2 run -it --rm  python:3.11.10-bullseye bash
root@92be827d2396:/# pip install cryptography==43.0.3 --index-url https://www.piwheels.org/simple --extra-index-url https://pypi.org/simple --prefer-binary
Looking in indexes: https://www.piwheels.org/simple, https://pypi.org/simple
Collecting cryptography==43.0.3
  Downloading https://www.piwheels.org/simple/cryptography/cryptography-43.0.3-cp37-abi3-linux_armv7l.whl (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 826.2 kB/s eta 0:00:00
Collecting cffi>=1.12 (from cryptography==43.0.3)
  Downloading https://www.piwheels.org/simple/cffi/cffi-1.17.1-cp311-cp311-linux_armv7l.whl (384 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 384.5/384.5 kB 568.2 kB/s eta 0:00:00
Collecting pycparser (from cffi>=1.12->cryptography==43.0.3)
  Downloading pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Downloading pycparser-2.22-py3-none-any.whl (117 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.6/117.6 kB 789.6 kB/s eta 0:00:00
Installing collected packages: pycparser, cffi, cryptography
Successfully installed cffi-1.17.1 cryptography-43.0.3 pycparser-2.22
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
root@92be827d2396:/# python
Python 3.11.10 (main, Dec  4 2024, 05:42:26) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cryptography.hazmat.primitives.ciphers
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/primitives/ciphers/__init__.py", line 11, in <module>
    from cryptography.hazmat.primitives.ciphers.base import (
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 10, in <module>
    from cryptography.hazmat.bindings._rust import openssl as rust_openssl
ImportError: libssl.so.3: cannot open shared object file: No such file or directory
>>>
```

Am I doing something wrong?

**Comment by bennuttall** [comment]
This is the same issue as #464. I've removed those builds now.

You'll have to either pin an older version or build it from source.
