### ISSUE TITLE
librosa failing to install on Raspbaery Pi 3

### ISSUE THREAD

**Issue by ksaye** [piwheels/packages#50]
Package name: librosa
Issue type: Broken package
Link to PyPI page: https://pypi.org/project/librosa/
Link to piwheels page: https://www.piwheels.org/project/librosa/
Version: e.g. all
Python version: e.g. 3.5
More information:

```bash
pip3 install librosa

root@raspberrypi:~# pip3 install librosa
Collecting librosa
  Using cached https://www.piwheels.org/simple/librosa/librosa-0.7.0-py3-none-any.whl
Requirement already satisfied: numpy>=1.15.0 in /usr/local/lib/python3.5/dist-packages (from librosa)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.5/dist-packages (from librosa)
Requirement already satisfied: six>=1.3 in /usr/lib/python3/dist-packages (from librosa)
Collecting audioread>=2.0.0 (from librosa)
  Using cached https://www.piwheels.org/simple/audioread/audioread-2.1.8-py3-none-any.whl
Requirement already satisfied: scikit-learn!=0.19.0,>=0.14.0 in /usr/local/lib/python3.5/dist-packages (from librosa)
Collecting soundfile>=0.9.0 (from librosa)
  Using cached https://files.pythonhosted.org/packages/68/64/1191352221e2ec90db7492b4bf0c04fd9d2508de67b3f39cbf093cd6bd86/SoundFile-0.10.2-py2.py3-none-any.whl
Collecting numba>=0.38.0 (from librosa)
  Using cached https://www.piwheels.org/simple/numba/numba-0.45.1-cp35-cp35m-linux_armv7l.whl
Requirement already satisfied: decorator>=3.0.0 in /usr/local/lib/python3.5/dist-packages (from librosa)
Requirement already satisfied: joblib>=0.12 in /usr/local/lib/python3.5/dist-packages (from librosa)
Collecting resampy>=0.2.0 (from librosa)
  Using cached https://www.piwheels.org/simple/resampy/resampy-0.2.2-py3-none-any.whl
Collecting cffi>=1.0 (from soundfile>=0.9.0->librosa)
  Using cached https://www.piwheels.org/simple/cffi/cffi-1.12.3-cp35-cp35m-linux_armv7l.whl
Collecting llvmlite>=0.29.0dev0 (from numba>=0.38.0->librosa)
  Using cached https://files.pythonhosted.org/packages/aa/48/f05704c49e9b7a092d6f1799f924bb5bf60ba58c08f946bcacd139809f2c/llvmlite-0.29.0.tar.gz
  Ignoring enum34: markers 'python_version < "3.4"' don't match your environment
Collecting pycparser (from cffi>=1.0->soundfile>=0.9.0->librosa)
  Using cached https://www.piwheels.org/simple/pycparser/pycparser-2.19-py2.py3-none-any.whl
Building wheels for collected packages: llvmlite
  Running setup.py bdist_wheel for llvmlite ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-exct70kd/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpe1d932dipip-wheel- --python-tag cp35:
  running bdist_wheel
  /usr/bin/python3 /tmp/pip-build-exct70kd/llvmlite/ffi/build.py
  LLVM version... 3.8.1

  Traceback (most recent call last):
    File "/tmp/pip-build-exct70kd/llvmlite/ffi/build.py", line 168, in <module>
      main()
    File "/tmp/pip-build-exct70kd/llvmlite/ffi/build.py", line 158, in main
      main_posix('linux', '.so')
    File "/tmp/pip-build-exct70kd/llvmlite/ffi/build.py", line 120, in main_posix
      raise RuntimeError(msg)
  RuntimeError: Building llvmlite requires LLVM 7.0+ Be sure to set LLVM_CONFIG to the right executable path.
  Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.

  error: command '/usr/bin/python3' failed with exit status 1

  ----------------------------------------
  Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: audioread, pycparser, cffi, soundfile, llvmlite, numba, resampy, librosa
  Running setup.py install for llvmlite ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-exct70kd/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-i38x_p4n-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    got version from file /tmp/pip-build-exct70kd/llvmlite/llvmlite/_version.py {'version': '0.29.0', 'full': '491dcbaa0a995686da65da9c84774b552b738a9e'}
    running build_ext
    /usr/bin/python3 /tmp/pip-build-exct70kd/llvmlite/ffi/build.py
    LLVM version... 3.8.1

    Traceback (most recent call last):
      File "/tmp/pip-build-exct70kd/llvmlite/ffi/build.py", line 168, in <module>
        main()
      File "/tmp/pip-build-exct70kd/llvmlite/ffi/build.py", line 158, in main
        main_posix('linux', '.so')
      File "/tmp/pip-build-exct70kd/llvmlite/ffi/build.py", line 120, in main_posix
        raise RuntimeError(msg)
    RuntimeError: Building llvmlite requires LLVM 7.0+ Be sure to set LLVM_CONFIG to the right executable path.
    Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.

    error: command '/usr/bin/python3' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-exct70kd/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-i38x_p4n-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-exct70kd/llvmlite/
root@raspberrypi:~#
```
system info:
root@raspberrypi:~# uname -a
Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
root@raspberrypi:~# cat /etc/issue
Raspbian GNU/Linux 9 \n \l
root@raspberrypi:~#

environment setup:
apt-get update \
    && apt-get install -y \
    libboost-python-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    liblapack-dev \
    libblas-dev \
    libatlas-base-dev \
    libhdf5-serial-dev \
    libhdf5-dev \
    gfortran \
    python3.5 \
    llvm-dev

export LLVM_CONFIG=/usr/bin/llvm-config

**Comment by bennuttall** [comment]
The issue is not with librosa, it's with llvmlite. See Issue #33 and https://github.com/numba/llvmlite/issues/314

**Comment by ksaye** [comment]
thank you!
