### ISSUE TITLE
Missing package: Shapely

### ISSUE THREAD

**Issue by topshed** [piwheels/packages#65]
Package name: shapely
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/shapely
Link to piwheels page: https://www.piwheels.org/project/shapely
Version: 1.5.10 and above
Python version: all
I am the maintainer: No
More information:

```bash
sudo pip3 install shapely
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting shapely
  Using cached https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz
    Complete output from command python setup.py egg_info:
    Failed `CDLL(libgeos_c.so.1)`
    Failed `CDLL(libgeos_c.so)`
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-o64u3s06/shapely/setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "/tmp/pip-install-o64u3s06/shapely/shapely/_buildcfg.py", line 167, in <module>
        fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])
      File "/tmp/pip-install-o64u3s06/shapely/shapely/_buildcfg.py", line 161, in load_dll
        libname, fallbacks or []))
    OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-o64u3s06/shapely/
```

**Comment by bennuttall** [comment]
Looks like `sudo apt-get install libgeos-dev` will fix it - I'll add it to the build script and get these rebuilt.

**Comment by bennuttall** [comment]
Installed, they're being requeued now but it'll take a while as there are so many versions

**Comment by bennuttall** [comment]
Done!
