### ISSUE TITLE
Pip Install SCIPY Error

### ISSUE THREAD

**Issue by rob26r** [piwheels/packages#75]
I've had many issues installing issues on my Raspberry PI 4.  I just reinstalled the NOOBS software on my PI and followed the install scipy instructions on this page https://www.piwheels.org/.

I followed all the instructions and getting the error message below:

```bash
(testpip) pi@raspberrypi:~ $ pip install scipy
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting scipy
  Downloading https://files.pythonhosted.org/packages/04/ab/e2eb3e3f90b9363040a3d885ccc5c79fe20c5b8a3caa8fe3bf47ff653260/scipy-1.4.1.tar.gz (24.6MB)
     |████████████████████████████████| 24.6MB 95kB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /home/pi/testpip/bin/python3 /home/pi/testpip/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp7l5e2ug7
         cwd: /tmp/pip-install-m2v4f51k/scipy
    Complete output (44 lines):
    setup.py:420: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /tmp/pip-modern-metadata-_3e_m5u_'), proceeding with generating Cython sources and expanding templates
      ' '.join(sys.argv[1:])))
    Traceback (most recent call last):
      File "/tmp/pip-build-env-6x0mqi49/overlay/lib/python3.7/site-packages/numpy/core/__init__.py", line 16, in <module>
        from . import multiarray
    ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/pi/testpip/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
        main()
      File "/home/pi/testpip/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/pi/testpip/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 110, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-6x0mqi49/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 156, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-6x0mqi49/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 237, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/tmp/pip-build-env-6x0mqi49/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 540, in <module>
        setup_package()
      File "setup.py", line 516, in setup_package
        from numpy.distutils.core import setup
      File "/tmp/pip-build-env-6x0mqi49/overlay/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
        from . import add_newdocs
      File "/tmp/pip-build-env-6x0mqi49/overlay/lib/python3.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
        from numpy.lib import add_newdoc
      File "/tmp/pip-build-env-6x0mqi49/overlay/lib/python3.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
        from .type_check import *
      File "/tmp/pip-build-env-6x0mqi49/overlay/lib/python3.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
        import numpy.core.numeric as _nx
      File "/tmp/pip-build-env-6x0mqi49/overlay/lib/python3.7/site-packages/numpy/core/__init__.py", line 26, in <module>
        raise ImportError(msg)
    ImportError:
    Importing the multiarray numpy extension module failed.  Most
    likely you are trying to import a failed build of numpy.
    If you're working with a numpy git repo, try `git clean -xdf` (removes all
    files not under version control).  Otherwise reinstall numpy.
    
    Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/pi/testpip/bin/python3 /home/pi/testpip/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp7l5e2ug7 Check the logs for full command output.
```

Can someone please tell me what I'm doing wrong because I've been spinning my wheels for too long.  Thanks.

**Comment by bennuttall** [comment]
We provide github issue templates which make it easier for us to follow-up on issues, but you haven't used one. Can you please use the templates in future? 

https://github.com/piwheels/packages/issues/new/choose

The issue you are having is not caused by piwheels. The file you downloaded came from PyPI, not from piwheels: 

```
Collecting scipy
  Downloading https://files.pythonhosted.org/packages/04/ab/e2eb3e3f90b9363040a3d885ccc5c79fe20c5b8a3caa8fe3bf47ff653260/scipy-1.4.1.tar.gz (24.6MB)
```

It looks like the latest versions of scipy failed to build on piwheels. I'll open a new issue for that and look into it.

Have you read the instructions on the scipy page? https://www.piwheels.org/project/scipy/

```bash
sudo apt install libatlas3-base libgfortran5
sudo pip3 install scipy
```

From your report it looks like installing `libatlas3-base` will resolve your issue.

**Comment by rob26r** [comment]
Thanks for the quick response.  As you can tell I'm completely new to this. My apologies, will use the github issues template going forward. I followed the instructions from https://www.piwheels.org/project/scipy/ and still getting an error message.  I will post on the github issues page.
