### ISSUE TITLE
Broken package: numpy

### ISSUE THREAD

**Issue by liffiton** [piwheels/packages#9]
Broken package
Package name: `numpy`
Version: `1.15.4`
More information:

I get an ImportError when importing numpy.  I have chased down whatever non-python package dependencies I could, and the error doesn't look like a missing library.  I have `libatlas-base-dev` installed.  The error:

```
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: /usr/local/lib/python3.5/dist-packages/numpy/core/multiarray.cpython-35m-arm-linux-gnueabihf.so: undefined symbol: cblas_sgemm

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python3.5/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: /usr/local/lib/python3.5/dist-packages/numpy/core/multiarray.cpython-35m-arm-linux-gnueabihf.so: undefined symbol: cblas_sgem
```

In case its helpful:

```
$ ldd /home/pi/.local/lib/python3.5/site-packages/numpy/core/multiarray.cpython-35m-arm-linux-gnueabihf.so
        linux-vdso.so.1 (0x7ebf2000)
        /usr/lib/arm-linux-gnueabihf/libarmmem.so (0x76e0a000)
        libf77blas.so.3 => /usr/lib/libf77blas.so.3 (0x76de1000)
        libcblas.so.3 => /usr/lib/arm-linux-gnueabihf/libcblas.so.3 (0x76d87000)
        libatlas.so.3 => /usr/lib/libatlas.so.3 (0x76b0f000)
        libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x76a90000)
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76a67000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76928000)
        /lib/ld-linux-armhf.so.3 (0x76f93000)
        libgfortran.so.3 => /usr/lib/arm-linux-gnueabihf/libgfortran.so.3 (0x76873000)
        libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0x76846000)
        libf2c.so.2 => /usr/lib/arm-linux-gnueabihf/libf2c.so.2 (0x7681d000)
```

This is on Raspbian Lite.

**Comment by MttTst** [comment]
@RobertLucian I spend all day struggling with this issue, 1.13.3 version works fine for me too. Thanks for help.

**Comment by C-Bouthoorn** [comment]
Here to confirm. Removed every single trace of numpy from my raspi 3, went into a virtualenv and did `pip3 install numpy` followed by `python -m numpy` and it just keeps crashing. Will try 1.13.3 in a moment since that seems to work for others.


```$ python3 -m numpy
Traceback (most recent call last):
  File "/home/pi/numpy-env/lib/python3.5/site-packages/numpy/core/__init__.py", line 40, in <module>
    from . import multiarray
  File "/home/pi/numpy-env/lib/python3.5/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/pi/numpy-env/lib/python3.5/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: /home/pi/numpy-env/lib/python3.5/site-packages/numpy/core/_multiarray_umath.cpython-35m-arm-linux-gnueabihf.so: undefined symbol: cblas_sgemm

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/numpy-env/lib/python3.5/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/pi/numpy-env/lib/python3.5/site-packages/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /home/pi/numpy-env/bin/python3),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: /home/pi/numpy-env/lib/python3.5/site-packages/numpy/core/_multiarray_umath.cpython-35m-arm-linux-gnueabihf.so: undefined symbol: cblas_sgemm
```

```
$ ldd /home/pi/numpy-env/lib/python3.5/site-packages/numpy/core/_multiarray_umath.cpython-35m-arm-linux-gnueabihf.so
	linux-vdso.so.1 (0x7e8d3000)
	/usr/lib/arm-linux-gnueabihf/libarmmem.so (0x76d48000)
	libf77blas.so.3 => /usr/lib/libf77blas.so.3 (0x76d10000)
	libcblas.so.3 => /usr/lib/arm-linux-gnueabihf/libcblas.so.3 (0x76cb6000)
	libatlas.so.3 => /usr/lib/libatlas.so.3 (0x76a3e000)
	libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x769bf000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76996000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76857000)
	/lib/ld-linux-armhf.so.3 (0x76f6d000)
	libgfortran.so.3 => /usr/lib/arm-linux-gnueabihf/libgfortran.so.3 (0x767a2000)
	libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0x76775000)
	libf2c.so.2 => /usr/lib/arm-linux-gnueabihf/libf2c.so.2 (0x7674c000)
```

```
$ uname -r
4.19.42-v7+
```

```
$ apt list *blas* | grep installed
libblas-common/oldstable,now 3.7.0-2 armhf [installed,automatic]
libblas-dev/oldstable,now 3.7.0-2 armhf [installed,automatic]
libblas3/oldstable,now 3.7.0-2 armhf [installed,automatic]
libcblas-dev/oldstable,now 3.2.1+dfsg-1 armhf [installed]
libcblas3/oldstable,now 3.2.1+dfsg-1 armhf [installed,automatic]
libopenblas-base/oldstable,now 0.2.19-3+rpi1 armhf [installed]
libopenblas-dev/oldstable,now 0.2.19-3+rpi1 armhf [installed]
```

**Comment by elektronika-ba** [comment]
Nothing worked for my Raspbery Pi 3, so I had to re-install Python, but now with **fpectl** included.

`#download Python (in my case v3.5.6)
cd
wget https://www.python.org/ftp/python/3.5.6/Python-3.5.6.tgz
tar -zxvf Python-3.5.6.tgz
cd Python-3.5.6

# start the installation
**./configure --with-fpectl**
make -j4
sudo make install

# free SD card space
cd
sudo rm -fr ./Python-3.5.6*
`
